### PR TITLE
add config file for antv/ava

### PR DESCRIPTION
**Pull request by jiazhewang**
Add algolia search to our opensource project: [https://ava.antv.vision/](https://ava.antv.vision/)

with issue https://github.com/algolia/docsearch-configs/issues/2740

# Pull request motivation(s)

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### CODE REVIEW

**Comment by shortcuts** [comment]
Pending until apply #2740

**Comment by jiazhewang** [comment]
The website is now ready.

**Comment by shortcuts** [comment]
@jiazhewang 

Please reply to the email I just sent you so I can deploy your config!

**Comment by jiazhewang** [comment]
> @jiazhewang
> 
> Please reply to the email I just sent you so I can deploy your config!

done.

**Review by shortcuts — APPROVED** [review]

**Pull request merged**
