### PR TITLE
Change start_urls to prod

### PR DESCRIPTION
**Pull request by justinwhall**

### CODE REVIEW

**Comment by justinwhall** [comment]
Hi @s-pace! This is not ready to merge yet. I'm assuming this will work as expected? Once you do merge this, the next time your crawler runs, it'll run on our production site which will soon by the same site that is --> [Here](http://sendgrid-knowledge-center-staging.s3-website-us-east-1.amazonaws.com/)

If so, I'll pop back in and give the go ahead when we are ready. Thanks!

**Comment by justinwhall** [comment]
OK, good to go here!

**Comment by s-pace** [comment]
Lucky I am on my laptop late ahah

**Comment by justinwhall** [comment]
Awesome! We some temporary code in place so it'll work either way for now. Thanks again!

**Comment by justinwhall** [comment]
Wow! That updated fast!

**Comment by ksigler7** [comment]
thanks so much @s-pace - you are awesome!

**Comment by s-pace** [comment]
You are very welcome. Yep the crawl takes few minutes. Hope you like it, feel free to let us know any wondering you have!

**Comment by pixelastic** [comment]
**That** is teamwork, well done all.

If I may, I think you have some styling issues with the dropdown:
image

(missing borders, shadows and the Algolia logo)

We just recently rewrote our own documentation about styling the dropdown here: https://community.algolia.com/docsearch/styling.html

Let us know if it helped you tweak it as you wanted, and if not let us know as well so we can improve our docs :)

**Comment by justinwhall** [comment]
Thanks for the feedback @pixelastic. I'll pass along your suggestions to the UI/UX team.

**Pull request merged**
