### PR TITLE
Add SendGrid docs

### PR DESCRIPTION
**Pull request by smendes**
# Pull request motivation(s)

We would like to extend the index with SendGrid's documentation placed under the same platform but under a different domain.

Let me know if you have any questions! Thanks!

### What is the current behaviour?

The current behaviour is to only crawl https://twilio.com/docs

### What is the expected behaviour?

We would like to have results from https://twilio.com/docs as well as https://docs.sendgrid.com

### CODE REVIEW

**Comment by maylonpedroso** [comment]
:+1:

**Comment by shortcuts** [comment]
Hey, do you want to have results from both domains under the same search? If that's not the case, I'd suggest to add [these parameters](https://docsearch.algolia.com/docs/config-file/#using-custom-tags) to your DocSearch instance before the merge

**Comment by maylonpedroso** [comment]
Hi @shortcuts! Yes, we want to have the results from both `docs.sendgrid.com` and `www.twilio.com/docs` under the same search.

**Comment by shortcuts** [comment]
Cool! Then you can merge the main branch so I can merge the PR!

**Pull request merged**
