### PR TITLE
Update the domain to open.lianlianpay.com

### PR DESCRIPTION
**Pull request by lianlianNex**
Looks like the config is reverted. Please help to merge since we are going to abort openllp.lianlianpay.com

### CODE REVIEW

**Comment by s-pace** [comment]
👋 @lianlianNex 

Could you make https://open.lianlianpay.com/docs/guides/overview available please?

**Comment by lianlianNex** [comment]
Hey @s-pace , isn't it working on your side as we discussed in PR #583 ? The page [https://open.lianlianpay.com/docs/guides/overview](https://open.lianlianpay.com/docs/guides/overview) does work from our side(CN mainland) as well as US. Could you please provide some details about where you are currently stuck in? Below is how the page looks like from our side.
image

**Comment by lianlianNex** [comment]
Currently https://openllp.lianlianpay.com is using exactly the same settings as the one for https://open.lianlianpay.com btw.

**Comment by s-pace** [comment]
It looks like we can only crawl https://open.lianlianpay.com/docs/guides/overview/

Could you provide us an updated sitemap please?

**Comment by lianlianNex** [comment]
Strange, the other sites, for ex,  [https://open.lianlianpay.com/docs/receive-money/express/overview](https://open.lianlianpay.com/docs/receive-money/express/overview) is not avaliable for crawler? 
I remember we haven't applied any settings against crawler for this site. Thanks for your feedback, checking now.

**Comment by s-pace** [comment]
This URL returned a `301`

**Comment by s-pace** [comment]
There is plenty of tools available depending on your codebase.

You only need to [respect this protocol](https://www.sitemaps.org/).

**Comment by lianlianNex** [comment]
Just to confirm, are you able to crawl [https://openllp.lianlianpay.com/docs/receive-money/express/overview](https://openllp.lianlianpay.com/docs/receive-money/express/overview) now?  Cause I noticed there are two 301 requests as well. 
image

It might be the redirect from HTTP to HTTPS

**Comment by s-pace** [comment]
No we can only crawl https://openllp.lianlianpay.com/docs/receive-money/express/overview/ (note the trailing /). We can only crawl it because it is an explicit `start_url`

**Comment by lianlianNex** [comment]
Thanks a lot, I will make a sitemap soon

**Pull request closed without merging**
