### PR TITLE
brew_all: re-add analytics pages

### PR DESCRIPTION
**Pull request by Rylan12**
# Pull request motivation(s)

Follow up to #3931 and #3922. See https://github.com/algolia/docsearch-configs/pull/3931#issuecomment-814530447

The analytics pages were intentionally excluded because they were making the crawl timeout. However, it would be helpful for these pages to still show up. The formulae linked on the pages, though, need not appear in the search.

Link showing maintainership: https://github.com/Homebrew/brew#who-we-are

Sitemaps: https://brew.sh/sitemap.xml, https://formulae.brew.sh/sitemap.xml

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

Searching for "analytics" or "formula install events" don't return the expected pages on https://brew.sh and https://formulae.brew.sh.

### What is the expected behaviour?

Searching for "analytics" would show a result for https://formulae.brew.sh/analytics/. Searching for formula install events would show results for pages like https://formulae.brew.sh/analytics/install/30d/ and https://formulae.brew.sh/analytics-linux/install/30d/.

##### NB: Do you want to request a **feature** or report a **bug**?

I'd classify this as a bug

##### NB2: Any other feedback / questions ?

I've copied this change from the [gist](https://gist.github.com/shortcuts/0d348d9f77415e85ecbfc120f1e3520d#file-brew_all-json-L70-L82) that was linked in https://github.com/algolia/docsearch-configs/pull/3931#issuecomment-815016964. I've looked over it to verify that it seems to fit what I'm looking for, but I'm not super familiar with these configuration files so it's possible that I'm misunderstanding what this will do.

One thing I'm not sure about is whether the 30d/90d/365d distinction will be handled by the search? For each analytics category, we have three different time periods (which really is three different pages) so, ideally, each one would show up in the search so the user to navigate directly to the one they want.

Also, I don't think we need to include the `/api/*` entries in the table on https://formulae.brew.sh/analytics/. I think these will be automatically excluded because they are JSON files and should be excluded by the `stop_urls` entry.

### CODE REVIEW

**Comment by shortcuts** [comment]
Hi @Rylan12,

In https://github.com/algolia/docsearch-configs/pull/3945/commits/6819f495a1d2063be3221fbe49dbf39ef7f5184e, I've updated the config so the above pages will show up.

The only issue is, typing something like `formula install events` will pop the pages with the same name for all the endpoints, unless something like `formula 30d` or something like this is typed. (which will show the `code` tag for the JSON api, as this is the only possible distinction)

If possible on your side, adding the time distinction to the `h2` could solve this issue.

**Comment by Rylan12** [comment]
Thanks, @shortcuts.

> If possible on your side, adding the time distinction to the `h2` could solve this issue.

Good idea, I'll open a PR. It probably makes sense for that to be in there, anyway.

**Comment by shortcuts** [comment]
Here's the results with the `h3` selector for now, which won't be needed on updated on your side.

Screenshot 2021-04-12 at 14 13 45

Would you like to merge this version or wait for the new one? @Rylan12

**Comment by Rylan12** [comment]
Thanks, @shortcuts. I don't see any rush here, so may as well wait for https://github.com/Homebrew/formulae.brew.sh/pull/450 to be merged.

**Comment by Rylan12** [comment]
@shortcuts that pull request has now been merged and the changes are live (see e.g. https://formulae.brew.sh/analytics/install/30d/)

**Comment by shortcuts** [comment]
Looks good @Rylan12 ! The new crawl task will be queued after the merge

**Comment by Rylan12** [comment]
Thanks, @shortcuts!

**Pull request merged**
