### PR TITLE
Update admin doc for Pydio 8

### PR DESCRIPTION
**Pull request by cdujeu**
Hi, we are upgrading our docs for next release. Thx.

### CODE REVIEW

**Comment by maxiloc** [comment]
Thanks. Deploying right now.

**Comment by cdujeu** [comment]
salut @maxiloc, small questions : is it possible to know when the indexation is run, and is there a log available somewhere? I miss some results in my search but i'm not sure whether it's a config issue or because indexation is not (yet) up-to-date.
thx in advance

**Comment by maxiloc** [comment]
We have the log on our side, but we don't have a way for you to access it.
Last run was 15 May 2017 11:10:37 GMT

**Comment by cdujeu** [comment]
can you quickly check if you see many pages starting with pydio.com/en/docs/v8/[....] properly parsed?

**Comment by maxiloc** [comment]
I re-run the crawler just to be sure, I see around 40 page which from v8

**Comment by cdujeu** [comment]
.. and i have better results now! Thank you so much :-)

**Pull request merged**
