### PR TITLE
index the 3.4 directory instead of 3.3

### PR DESCRIPTION
**Pull request by acmetech**
Updating the config to reflect the doc versions that I would like to be searchable.

### CODE REVIEW

**Comment by s-pace** [comment]
Updated and deployed https://github.com/algolia/docsearch-configs/commit/4bea08d8bd4c2ae967cd891b7c39e1fd239f2b69

Please do not forget to check that the selectors do match something from your HTML. Keeping the same layout is a good way to ensure the consistency between every versions.

Changes are live :)

**Comment by acmetech** [comment]
Thank you.

Is the underlying crawler configured so that I can do version specific queries using algoliaOptions: { 'facetFilters': ["version:$VERSION"]?

**Comment by s-pace** [comment]
Yes @acmetech

**Comment by s-pace** [comment]
Yes @acmetech

**Comment by acmetech** [comment]
I receive results when I query with 'facetFilters': ["version:3.4"], but I get not results when using 'facetFilters': ["version:4.1"]

**Comment by acmetech** [comment]
It's working. Thank you

**Pull request merged**
