### PR TITLE
Updated URL

### PR DESCRIPTION
**Pull request by norfali**
Updated Morningstar Design System's config settings

### CODE REVIEW

**Comment by s-pace** [comment]
👋 @norfali 

Are you interested in featuring DocSearch on your newest version ? We can add a tag for the `legacy` part an one for [the newest `v3` version](https://designsystem.morningstar.com/).

**Comment by norfali** [comment]
> 👋 @norfali
> 
> Are you interested in featuring DocSearch on your newest version ? We can add a tag for the `legacy` part an one for [the newest `v3` version](https://designsystem.morningstar.com/).

Hey @s-pace! Our new version was released only this morning and we actually have a ticket coming up soon to add search feature so once it is all stable and working correctly, we will start looking. :)

**Comment by vhicks** [comment]
@s-pace Hello, I am on the morningstar design system team with @norfali. We are ready to add docsearch to our new site. We have iframe content that we will need to surface in the results e.g. https://designsystem.morningstar.com/components/button/?version=3.0.7&tab=variations

Is there a way to confirm that the selectors in the iframe will show up in search results?

**Comment by s-pace** [comment]
@vhicks I checked it on your website and we are not able to index contente from `<iframe/>`. Would it be possible to not rely on an iframe? Can you also [provide a sitemap.xml](https://docsearch.algolia.com/docs/config-file/#sitemaps) so that we are sure we do not miss any page from your website.

**Pull request merged**
