### PR TITLE
Update material-ui.json

### PR DESCRIPTION
**Pull request by oliviertassinari**
Work around for #190. It should only match once and not twice.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
It seems that this fix hasn't been deployed. I'm right to think so?

**Comment by ElPicador** [comment]
I've checked, it was deployed

**Comment by oliviertassinari** [comment]
@ElPicador Thanks for checking it out. Then, something is wrong, this change hasn't changed the indexed data. I will have a second look.

**Comment by ElPicador** [comment]
My mistake, I've reviewed this too quickly.
The selector should be a XPATH selector, not CSS.
So either change it to XPATH, or only but a string with the selector

**Comment by oliviertassinari** [comment]
@ElPicador Awesome, I will fix this 👍

**Comment by oliviertassinari** [comment]
CSS path seems to be supported but I won't try the devil `//*[contains(@class, 'algolia-drawer')]//*[contains(@class, 'algolia-lvl0')]` selector should do the job. hold my beer, a PR is coming.

https://github.com/algolia/docsearch-configs/blob/7029f78a9152fd71201294418011ee18f26008ab/configs/flowtype.json#L15

**Comment by oliviertassinari** [comment]
Looks at the docs, I'm getting more confident, let's try the devil.

**Pull request merged**
