### PR TITLE
fix `stop_urls` typo on material-ui

### PR DESCRIPTION
**Pull request by siriwatknp**
# Pull request motivation(s)

### What is the current behaviour?

Currently, the url with `?expand-path` is indexed (we don't want it) which cause the issue when search with `theme`.
Try it here, https://material-ui.com/

Screen Shot 2564-09-15 at 11 44 16

### What is the expected behaviour?

I have tested with this change, it seems to fix the issue. Here is the new search result:

Screen Shot 2564-09-15 at 11 48 03

### CODE REVIEW

**Comment by siriwatknp** [comment]
Another question (not related to the PR), I wonder how to have nested node like tailwindcss or the official docsearch site?

### Tailwindcss
Screen Shot 2564-09-15 at 11 51 27

### Docsearch
Screen Shot 2564-09-15 at 11 52 11

**Comment by shortcuts** [comment]
Hey @siriwatknp

Tailwindcss, Docusaurus or Vuepress websites uses the next version of DocSearch! It is currently in alpha but already widely used, and we are planning to go for a stable version soon.

It's available for [JavaScript](https://www.npmjs.com/package/@docsearch/js/v/alpha) and [React](https://www.npmjs.com/package/@docsearch/react/v/alpha) out of the box with the styling you can see on the DocSearch website.

You can see [our repository](https://github.com/algolia/docsearch/tree/next/) here on the `next` branch, and [some examples](https://github.com/algolia/docsearch/tree/next/examples).

**Comment by siriwatknp** [comment]
> Hey @siriwatknp
> 
> Tailwindcss, Docusaurus or Vuepress websites uses the next version of DocSearch! It is currently in alpha but already widely used, and we are planning to go for a stable version soon.
> 
> It's available for [JavaScript](https://www.npmjs.com/package/@docsearch/js/v/alpha) and [React](https://www.npmjs.com/package/@docsearch/react/v/alpha) out of the box with the styling you can see on the DocSearch website.
> 
> You can see [our repository](https://github.com/algolia/docsearch/tree/next/) here on the `next` branch, and [some examples](https://github.com/algolia/docsearch/tree/next/examples).

Okay, thanks. To be sure, it is not about the configuration but the version of docsearch js right?

**Comment by shortcuts** [comment]
> Okay, thanks. To be sure, it is not about the configuration but the version of docsearch js right?

Exactly, it's only related to the frontend, the config part doesn't change

**Pull request merged**
