### PR TITLE
Add new facetFilter

### PR DESCRIPTION
**Pull request by TribeWeb**
Hi Sylvain,
After the last changes, I could see the search results were populated. Thanks.
I want to try facet filtering on an attribute, "location". I've added a meta tag to each page:
<meta name="docsearch:location" content="coventry-university-group,cu-coventry,coventry-university">
I'll need to add this to the facetFilters in the search component - but is there anything else I need to do to make this work?
Thanks
Rich

### CODE REVIEW

**Comment by s-pace** [comment]
👋 @TribeWeb 

We wouldn't find any meta tags with the name `location`. Can you provide an URL of a page with these meta tag please?

It should be built this way:
```html
​<meta name="docsearch:location" content="<location>">
```

**Comment by TribeWeb** [comment]
Hi Sylvain,

Wow - you are quick!

https://wayfinder.coventry.ac.uk/services/centre-for-academic-writing.html <https://wayfinder.coventry.ac.uk/services/centre-for-academic-writing.html>



Can you see it now - and is that the right format?

Thanks

Richard

**Comment by s-pace** [comment]
If you want to define several values from the meta tags, you will need to comply with the following format:
```html
<meta name="docsearch:location" content='["coventry-university-group","coventry-university"]'>
```

**Comment by TribeWeb** [comment]
Hi Sylvain,

Thanks for spotting that format error - I think that’s looking ok now.



Is there anything else I need to cover?

Also - version 3 is looking great - I watched your introduction video last night.

Many thanks

Rich

**Comment by s-pace** [comment]
Thanks you @TribeWeb for your feedback. 

The meta tags is not ready yet. Currently your website include the following tag:
```html
<meta name="docsearch:location" content="[&quot;coventry-university-group&quot;,&quot;coventry-university&quot;,&quot;cu-coventry&quot;]">
```
while it should be:
```html
<meta name="docsearch:location" content='["coventry-university-group","coventry-university","cu-coventry"]'>
```
Please mind the use of simple and double quote

Let me know once this is ready.

Thanks

**Comment by TribeWeb** [comment]
Hi Sylvain,

Third time’s the charm?

How’s this one? - I’ve no idea how to remove the outer double quotes that wrap the string you recommended



Thanks

Richard

**Comment by s-pace** [comment]
Can you please avoid using HTM entity `&quot;` and use double quote character instead please? You might also want to move the meta tags within the `<head/>` section.

Currently, the HTML tags are as follow:
```html
<meta name="docsearch:location" content="'[&quot;coventry-university-group&quot;,&quot;coventry-university&quot;,&quot;cu-coventry&quot;]'">
```

Let us know once this is ready

**Comment by s-pace** [comment]
If it is easier for you. We can try out to swap `"` and `'`.

You can set either the meta tags as follow:

```html
<meta name="docsearch:location" content='["coventry-university-group","coventry-university","cu-coventry"]'>
```

or 

```html
<meta name="docsearch:location" content="['coventry-university-group','coventry-university','cu-coventry']">
```

**Comment by TribeWeb** [comment]
Hi Sylvain

That was a lot easier. Is that ok now?

Thanks for your patience and help.

Rich

**Comment by s-pace** [comment]
It is working now:

You're now a few steps away from having it working on your website:

- Update the snippets of your page

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: 'f7bb48a9f7a9ed440b7795ec1c42d80e',
  indexName: 'tribeserver',
  inputSelector: '#algolia-search-input',
  algoliaOptions: { 'facetFilters': ["lang:$LANG", "location:$LOCATION"] },
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>

- Replace $LANG with the lang you want to search on. The list of possible lang is extracted from your website thanks to the selector defined from your config
   So as of today you have: `en-US`

- Replace $LOCATION with the location you want to search on. The list of possible location is extracted from your website thanks to the meta tags you addedSo as of today you have:
`['coventry-university-group','coventry-university','coventry-university-london','cu-coventry','cu-london','cu-scarborough'], ['coventry-university-group','coventry-university','coventry-university-london','cu-coventry','cu-scarborough','cu-london','coventry-university-wroclaw'], ['coventry-university-group','coventry-university','coventry-university-london','cu-coventry','cu-scarborough','cu-london'], ['coventry-university-group','coventry-university','cu-coventry','cu-scarborough'], ['coventry-university-group','coventry-university','cu-coventry'], ['coventry-university-group','coventry-university'], ['coventry-university-group','coventry-university-london'], ['coventry-university-group','coventry-university-wroclaw'], ['coventry-university-group','cu-coventry','coventry-university','coventry-university-london'], ['coventry-university-group','cu-coventry','coventry-university'], ['coventry-university-group','cu-coventry','cu-london','cu-scarborough','coventry-university-london','coventry-university-wroclaw','coventry-university'], ['coventry-university-group','cu-coventry','cu-scarborough','coventry-university'], ['coventry-university-group','cu-coventry','cu-scarborough'], ['coventry-university-group','cu-coventry'], ['coventry-university-group','cu-london','cu-scarborough','cu-coventry','coventry-university'], ['coventry-university-group','cu-london'], ['coventry-university-group','cu-scarborough','cu-london','cu-coventry','coventry-university','coventry-university-london'], ['coventry-university-group','cu-scarborough','cu-london'], ['coventry-university-group','cu-scarborough'], ['coventry-university-wroclaw','cu-scarborough','cu-coventry','coventry-university-london','coventry-university-group'], ['cu-london','cu-scarborough','coventry-university-london','coventry-university-group','cu-coventry','coventry-university'], ['cu-london'], ['cu-scarborough','cu-coventry','cu-london','coventry-university-group','coventry-university'], ['cu-scarborough','cu-london','coventry-university-group','cu-coventry'], ['cu-scarborough','cu-london','coventry-university-wroclaw','coventry-university-group','cu-coventry'], ['cu-scarborough','cu-london','cu-coventry','coventry-university','coventry-university-wroclaw','coventry-university-london','coventry-university-group'], [undefined]`

  For example if you want to refine the search to the lang "en-US" and the location "['coventry-university-group']" just specify:
```js
 'facetFilters': ["lang:en-US", "location:['coventry-university-group']"]
```

**Comment by s-pace** [comment]
👋 @TribeWeb 

Actually it didn't work. The meta tags must be built in this way:
```html
<meta name="docsearch:location" content='["coventry-university-group","coventry-university","cu-coventry"]'>
```

Sorry for the confusion.

**Pull request merged**
