### PR TITLE
Update apache_camel.json

### PR DESCRIPTION
**Pull request by aashnajena**
# Pull request motivation(s)

- We use our own UI for presenting search results, so we had created our config file accordingly. [This commit](https://github.com/algolia/docsearch-configs/commit/77634d58dab0f46f7dfc020a7b7fae1e9b390fe2#diff-a63c497e1db6a7dcc07ef35536d19967) makes our config file a lot more structured, but it interferes with our UI a little. I've understood the motivation behind this commit and am hence making the following changes to improve our config file, while also keeping in mind our custom UI.

### What is the current behaviour?

- We had reserved lvl0 for "version numbers", but in case of "blogs" and default selectors, we are getting "blogs/documentation" as lvl0. I have changed lvl6 to reflect "versions", since only "algolia-pages" selector will have versions. For the rest, I have taken the changes from [this commit](https://github.com/algolia/docsearch-configs/commit/77634d58dab0f46f7dfc020a7b7fae1e9b390fe2#diff-a63c497e1db6a7dcc07ef35536d19967) into account.

### What is the expected behaviour?

- Versions, if present, should be displayed separately on the right side. For this, we want to reserve one level for extracting versions, and check if it's null or not from UI code.

##### NB: Do you want to request a **feature** or report a **bug**?

- No. We just want to improve our config file with these changes.
 
##### NB2: Any other feedback / questions ?

- No.

### CODE REVIEW

**Comment by aashnajena** [comment]
@zregvart is a maintainer of the camel-website repository and can approve these changes.

**Comment by aashnajena** [comment]
Are you suggesting that we add DocSearch-specific meta tags to our HTML code? Also, please note that we have an [ongoing PR](https://github.com/apache/camel-website/pull/444) to include the "Search by Algolia" logo in our search results.

**Comment by s-pace** [comment]
Thanks for the details @aashnajena 

Yes I would recommend you to add these specific meta tags. In the meantime, do you want me to merge this PR and give it a try? You can add these meta tags later on.

**Comment by aashnajena** [comment]
We will work on including these meta tags in the next couple of weeks. Please merge these changes for now (since we have the above-mentioned PR on hold due to this one).

**Comment by aashnajena** [comment]
@s-pace Has this config been successfully deployed? Can you please double check, because we're still seeing results according to the older version of this config file.

**Comment by s-pace** [comment]
👋 @aashnajena the crawl was deployed by https://github.com/algolia/docsearch-configs/pull/2133/commits/3b6f2716c3f46e463d7cf28ad5a5f7ad405a519b and the new changes introduces by #2286 are also deployed

**Comment by aashnajena** [comment]
Thank you! I can see the modified search results appearing now.

**Pull request merged**
