### PR TITLE
updates docksal selectors

### PR DESCRIPTION
**Pull request by shelane**
# Pull request motivation(s)
We have updated the top level selector and adjusted the rest of the levels up as well. We are hoping that this gets us the right level.

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

We are seeing a strange behavior with results displayed as you type.

algolia

### What is the expected behaviour?
The expected behavior is for the search results to display correctly.

##### NB2: Any other feedback / questions ?

We are taking a guess as to what to fix. We are starting with the selectors because we don't have the style class that was marked for lvl0. You can see our attempt at adding the Algolia code to our site: https://github.com/docksal/docksal/pull/893

### CODE REVIEW

**Comment by s-pace** [comment]
👋 @shelane 
We do not face any issue with the dropdown. Must be a CSS issue.
image

**Comment by s-pace** [comment]
I do not think this PR will fix this issue. Please review your CSS.

In the meantime, I have updated and deploy your config to better handled `_` as you can see here:
image

**Comment by shelane** [comment]
Thanks for the response. We are using Hugo Learn theme and I have only a few custom css beyond that. There are 3 specifically to prevent the Algolia css from resizing our search box and the surrounding positioning and to prevent the page body text from bleeding through onto the search box. I’ve tried changing the order of the css, but that did nothing.

**Comment by s-pace** [comment]
Please note that we crawl https://docs.docksal.io and not your staging website.

Using the CSS property `all: initial;`allow you to reset every CSS properties. Really helpful when you want to integrate one element without inherit from the global rules? Did you try it (even if browser support is not the best)

**Comment by shelane** [comment]
Resetting css properities with `all: initial` did not work. However, I did discover that the Hugo theme creates and defines the `searchbox` class and the Algolia stylesheet had one as well. I found that the cleanest approach in this case was to rename our class to `searchboxed` and include all the original theme css to our custom theme css and all is well. Thanks for your help!

**Pull request closed without merging**
