### PR TITLE
Update yiddishe-kop config

### PR DESCRIPTION
**Pull request by Yiddishe-Kop**
### Update Docsearch config

The docsearch on https://laravel-commerce.yiddishe-kop.com/ is not returning any results.
I hope this fixes it.

Thanks.

### CODE REVIEW

**Comment by Yiddishe-Kop** [comment]
Why is the CI saying that it's `missing nb_hits key`, when it's not missing?

**Comment by shortcuts** [comment]
> Why is the CI saying that it's `missing nb_hits key`, when it's not missing?

Hi, there was a trailing comma on the last object which was not supposed to be here

**Comment by Yiddishe-Kop** [comment]
How long does it take until the new config goes into effect?

**Comment by shortcuts** [comment]
It should be effective in the next 24 hours max!

**Pull request merged**
