### PR TITLE
add "/sips" to showing results

### PR DESCRIPTION
**Pull request by kiviok**
try fix this https://github.com/scala/docs.scala-lang/issues/1049#issuecomment-404524167

### CODE REVIEW

**Comment by jvican** [comment]
Thanks for the catch!

**Comment by jvican** [comment]
Can we also remove "/tutorials/tour/"?

**Comment by s-pace** [comment]
Thanks for the PR. 

Let's deploy it :)

**Comment by kiviok** [comment]
it's work 😀

**Pull request merged**
