### PR TITLE
configuration settings updated

### PR DESCRIPTION
**Pull request by alexvarsh**
# Pull request motivation(s)

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### CODE REVIEW

**Comment by alexvarsh** [comment]
Settings config changes are needed to improve visual presentation of Algolia's search results for
https://docs.tigera.io/

**Comment by s-pace** [comment]
👋 @alexvarsh 

Changes are live and deployed.

**Comment by alexvarsh** [comment]
Great, thank you!

Really appreciate your help,

Alex Varshavsky

**Comment by alexvarsh** [comment]
Hi Sylvain,

We need to disallow indexing for all agents other than Algolia.
Can you confirm that setting robots.txt to:

# Block all indexing for all agents
User-agent: *
Disallow: /

will not impact Algolia's search results?

Thx,
Alex V

**Comment by s-pace** [comment]
Hi @alexvarsh 

For some reasons, we do not respect robots.txt. Changing this will not affect us.

You can [define a specific `user_agent` from your configuration if needed](https://community.algolia.com/docsearch/config-file.html#user_agent-optional).

Cheers

**Comment by alexvarsh** [comment]
Hi Sylvain,

Thank you for your feedback,

Thx,
Alex V

**Pull request merged**
