### PR TITLE
add dazzling

### PR DESCRIPTION
**Pull request by jondot**
Adding dazzling. Bits I'm missing are `conversation_id` and `nb_hits`

Thanks!

### CODE REVIEW

**Comment by s-pace** [comment]
Awesome @jondot thank you for the PR. I will fill it with the missing information from your request.

Please note that your sitemap is not updated with http**S** URLS

**Comment by s-pace** [comment]
Credential and analytics invitation pending in your mailbox @jondot

**Comment by jondot** [comment]
thanks!

**Comment by jondot** [comment]
Confirmed integrated and search works well 😎

**Pull request closed without merging**
