### PR TITLE
Update akeneo.json for the 3.2 release

### PR DESCRIPTION
**Pull request by SamirBoulil**
Adds the 3.2 release. (planned to be live on 30th July)

### CODE REVIEW

**Comment by SamirBoulil** [comment]
Hello, it seems the algolia search bar is broken on our website for the 3.2 version ( https://docs.akeneo.com/3.2/index.html). 

Maybe there was something wrong with this PR, What steps can I follow to have this issue fixed ?

**Comment by s-pace** [comment]
This PR is being deployed. It will be done before EOD. Let’s have a look tomorrow if it is not working

**Comment by SamirBoulil** [comment]
The search bar is still broken today, is there some manual steps you can perform on your end ?

**Comment by s-pace** [comment]
Crawl will be done today. I have triggered it too late and akeneo has not be done yet. Will keep you in touch

**Comment by s-pace** [comment]
@samirboulil @shipow is running it so that you can test it asap

**Comment by s-pace** [comment]
@samirboulil ✅

**Comment by s-pace** [comment]
39 772 hits

**Comment by SamirBoulil** [comment]
Yes, the search bar is back! Thank you for the help!

**Pull request merged**
