### PR TITLE
blocking a specific URL from showing up in SendGrid docssearch

### PR DESCRIPTION
**Pull request by ksigler7**
# Pull request motivation(s)
We are releasing functionality in a beta and right now, we don't want this page to show up in any search results.

### What is the current behaviour?
Currently the page doesn't exist. We are deploying it today.
*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### What is the expected behaviour?

We're expecting this page not to show up in search results when we deploy it today

### CODE REVIEW

**Comment by ksigler7** [comment]
thanks @s-pace!!

**Comment by s-pace** [comment]
👋 @ksigler7 

It looks like that some custom code are currently failing. It is [broking the search](https://sendgrid.com/docs/ui/sending-email/getting-started-with-automation/). I can confirm you that your DocSearch index is working fine with the built-in UI

image

**Comment by ksigler7** [comment]
@s-pace - we are trying to block this page from showing up in the search results. is there another way we can do this with docsearch?

**Comment by ksigler7** [comment]
@s-pace - this is a great catch! we are working on a patch now from our side

**Pull request merged**
