### PR TITLE
Update goharbor config

### PR DESCRIPTION
**Pull request by OrlinVasilev**
# Pull request motivation(s)
We need update for the crawing of the website only under /docs
Also we need to properly handle the versions, so to search in only the selected version.

https://github.com/goharbor/community/blob/master/MAINTAINERS.md 

### What is the current behaviour?
Currently returns results from blogs, docs.. etc we need to limit that to docs only.

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### What is the expected behaviour?
To show only results in docs

### CODE REVIEW

**Comment by OrlinVasilev** [comment]
@jonasrosland

**Comment by OrlinVasilev** [comment]
@shortcuts can you take a look please

**Comment by shortcuts** [comment]
> Also we need to properly handle the versions, so to search in only the selected version.

You can use the following method to handle versioning on your DocSearch instance https://docsearch.algolia.com/docs/config-file/#using-regular-expressions

**Comment by OrlinVasilev** [comment]
@shortcuts 
We want to implement the same functionality as we have in 
https://github.com/algolia/docsearch-configs/blob/master/configs/velero.json

**Comment by shortcuts** [comment]
Make sense!

**Pull request merged**
