### PR TITLE
Update config

### PR DESCRIPTION
**Pull request by chudongvip**
Update config

### CODE REVIEW

**Comment by shortcuts** [comment]
Hi @chudongvip and @DyncMark,

Thanks for the PR.

It looks like the index your just referenced (**anyrtc_rtc-web**) for the new file doesn't exists.

As both of the config are pointing to the same domain as [your actual config](https://github.com/algolia/docsearch-configs/blob/841a9c4a892a8b3162df835d27cf4cc22e10fdc2/configs/anyrtc.json), you can merge them together under the same config file and use [custom tags](https://docsearch.algolia.com/docs/config-file/#using-custom-tags) to display the content you want based on the page you are.

Actually, the config **anyrtc.json** is already referencing the **rtc-web** endoint.

Let me know if you need any help with it.

**Comment by chudongvip** [comment]
Sorry, This is my fault, I may not understand the working principle, please help me delete 'anyrTC_RTC-web.json'.

**Comment by shortcuts** [comment]
Here you go! @chudongvip, the config should work for every domains.

Should I merge it or you'll do changes/tests to it?

**Comment by chudongvip** [comment]
The content I find on my site is not what I really want, so I'm not sure if I need to merge

**Comment by shortcuts** [comment]
The changes made on your config will be effective in the next 24 hours after the PR has been merged

**Comment by chudongvip** [comment]
Thank you, Sir. 

Here is a problem that needs your help.

This is my website https://docs.anyrtc.io contains some links, such as:
- https://docs.anyrtc.io/rtc-web (alias website rtc-web)
- https://docs.anyrtc.io/rtc-android (alias website rtc-android)
- https://docs.anyrtc.io/rtc-ios (alias website rtc-ios)
- https://docs.anyrtc.io/rtm-web (alias website rtm-web)
- ...

Click this links will jump to the website that built by [Docusaurus](https://v2.docusaurus.io/) and have [DocSearch](https://v2.docusaurus.io/docs/search) configured. 

 But the search results weren't what I wanted. See the screenshot below.

image

When I search the join keyword on the rtc-web site, The content of join in Site rtm-web is returned. I hope to return all these sites  or just match to the content is matched to the content on this site to do？

**Comment by shortcuts** [comment]
From what I understand, keeping your old version of the config is actually the best option to what you want to achieve.

- With the version that is live on your site, you are using [custom tags](https://docsearch.algolia.com/docs/config-file/#using-custom-tags) so if you add facet filters in your docsearch instance: 
```js
docsearch({
  […],
  algoliaOptions: {
    'facetFilters': ["tags:rtc-web"]
  },
});
```
You will be able to restrict the search results based on the tags.

- With the new version that you just updated, making a search from **any endpoint** will return results from **every endpoints**

**Comment by chudongvip** [comment]
> 据我了解，保留旧版本的配置实际上是实现目标的最佳选择。
> 
> * 对于您网站上的实时版本，您正在使用[自定义标记，](https://docsearch.algolia.com/docs/config-file/#using-custom-tags)因此，如果您在docsearch实例中添加构面过滤器，则：
> 
> ```js
> docsearch （{ 
>   [ … ] ，
>   algoliaOptions：{ 
>     'facetFilters'：[ “ tags：rtc-web” ] 
>   } ，
> } ）;
> ```
> 
> 您将能够基于标签限制搜索结果。
> 
> * 使用刚刚更新的新版本，从**任何端点**进行搜索**都**将返回**每个端点的**结果****

Thanks for your reply. I have tried the method you mentioned before, but it still doesn't work. When I actually search on the WEBSITE of rtc-web, I find the content in rtm-Android. May I invite you to take a look at my configuration of my project? https://github.com/chudongvip/ArRTCWebDocs/invitations. Please give me a hand.

**Comment by shortcuts** [comment]
Hi @chudongvip,

Your `algoliaOptions` were indeed correct but your config was missing `tags` in `attributesForFaceting` which means that it wasn't retrieving anything related to this attribute.

It should now be all good, let me know if there's any other issues with it.

The changes should be effective in the next 24 hours!

**Comment by DyncMark** [comment]
Hi bro,

Thank you very very very mush!   <https://emojipedia.org/thumbs-up/> Now all is well 👍 <https://emojipedia.org/thumbs-up/>.

Keep safe. Tanks again. 🤟

**Pull request merged**
