### PR TITLE
Add antv.alipay.com

### PR DESCRIPTION
**Pull request by afc163**
# Pull request motivation(s)

Add algolia search to our opensource project: https://github.com/antvis

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### CODE REVIEW

**Comment by afc163** [comment]
I am also submit this form: https://community.algolia.com/docsearch/#join-docsearch-program

Do I need to wait for reply?

**Comment by afc163** [comment]
How could I get antv's apiKey? https://github.com/antvis/gatsby-theme-antv/pull/35/files#diff-69ac7a1464863a9b558a3ca01d18c397R8

**Comment by s-pace** [comment]
👋 @afc163 

Thank you for the PR. I have deployed it. All details needed are available from the email thread. I have just replied to it.

**Comment by afc163** [comment]
Thx! 😊 @s-pace

**Pull request merged**
