### PR TITLE
Start urls added

### PR DESCRIPTION
**Pull request by woodyrew**
Added all the relevant sections that need indexing

### CODE REVIEW

**Comment by woodyrew** [comment]
@maxiloc Is it possible to provide a an estimation for when this could be looked at please?

**Comment by maxiloc** [comment]
Sorry I missed the PR let me merge that and deploy right now

**Comment by woodyrew** [comment]
Thanks :smile:

**Comment by maxiloc** [comment]
Just deployed it tell me if that worked for you

**Comment by maxiloc** [comment]
(Should be live in the new few minutes)

**Comment by woodyrew** [comment]
Thank you, looks like the extra sources are there and working.

**Pull request merged**
