### PR TITLE
Added salesforce vscode docs

### PR DESCRIPTION
**Pull request by ntotten**
Adding config for Salesforce Extensions for VS Code docs. Site will be live on Feb. 14th.

### CODE REVIEW

**Comment by s-pace** [comment]
Hi @ntotten,

Thank you for the PR. Could you still apply please? It will help to better communicate with you.

Thanks

**Comment by ntotten** [comment]
Done, thanks!

**Comment by s-pace** [comment]
Hi @ntotten,

It seems that https://forcedotcom.github.io/salesforcedx-vscode/ is not available yet. Please ping me or reply to the conversation created by email once your website is available. We will retry the crawl.

**Comment by ntotten** [comment]
Sorry, yeah. The site is launching on Thursday. Thanks!

**Comment by ntotten** [comment]
@s-pace The site is now live. Please let me know what you need from me to enable it. Thanks!

**Comment by s-pace** [comment]
You just need to update your current code with this one :)

```js
  docsearch({
    apiKey: '354d0738c025be4feb1208d80033ecfc', 
    indexName: 'salesforce_vscode', 
    inputSelector: '#search-landing-nav'
  });
```

**Comment by s-pace** [comment]
Please check your mailbox @ntotten, you will have more details regarding your DocSearch index :)

**Pull request merged**
