### PR TITLE
Consolidate Craft CMS configuration

### PR DESCRIPTION
**Pull request by mattstein**
Based on https://gist.github.com/shortcuts/bb68b63fa1fab4ce1a13d356597c71a9, further modified.

- Consolidates `craftcms_commerce` index into → `craftcms`.
    - Originally attempted to delete `configs/craftcms_commerce.json`, but caused Circle CI test to fail. 
- Designates sets via tag (as recommended).
- Removes `craftcms.com/docs/*` URLs that don’t need to be indexed.
- Reduces `selectors` set to default only.

This is following an email thread about the Craft CMS and Craft Commerce API reference DocSearch configs.

### CODE REVIEW

**Review by shortcuts — APPROVED** [review]

**Comment by mattstein** [comment]
@shortcuts I can update our projects quickly if you’d like to merge this. 

Do you know how long it’ll be between your merge and the indexes being updated so I can try and minimize search downtime?

**Comment by shortcuts** [comment]
> Do you know how long it’ll be between your merge and the indexes being updated so I can try and minimize search downtime?

It gets added to the crawl queue right after the merge, as it's constantly moving, it can take up to 24 hours but usually it's done under ~3 hours

**Comment by mattstein** [comment]
Okay, thank you! 👍

**Comment by mattstein** [comment]
Ready to merge at your convenience, @shortcuts.

**Pull request merged**
