### PR TITLE
Apply webpack.kr config to existing config

### PR DESCRIPTION
**Pull request by YukJiSoo**
# Pull request motivation(s)
- Updated the existing `webpack.js.org` config so that the function can be used on the `webpack.kr`.

### CODE REVIEW

**Comment by shortcuts** [comment]
Hi @YukJiSoo, are you a maintainer of the webpack English website?

Updating the config without adding the [`facetFilters`](https://docsearch.algolia.com/docs/required-configuration/#introduce-global-information-as-meta-tags) on the webpack-js.org website will also display the Korean results with the English ones, please open a PR on their repository to update DocSearch and let me know when I should merge this!

```js
docsearch({
  […],
  algoliaOptions: {
    'facetFilters': ["language:en"]
  },
  […],
});
```

Thanks

**Comment by YukJiSoo** [comment]
Hi @shortcuts 

First of all I am not maintainer of webpack english site.
I am the maintainer of the newly released Korean webpack site.

We do not want Korean results to be exposed on the webpack English site.

I think it is good to create a separate config to provide functions like webpack Chinese site.

**Comment by shortcuts** [comment]
Yes, I think this is the best option. 

I'll reply to your email with the credentials for the Korean endpoint.

**Comment by YukJiSoo** [comment]
@shortcuts 
Thank you! Please reply to `dl_webpack_kr@linecorp.com`.

**Pull request closed without merging**
