### PR TITLE
Fixed selector for text (ezplatform doc)

### PR DESCRIPTION
**Pull request by damianz5**
After some tests we would like to add table content to text selector

### CODE REVIEW

**Comment by s-pace** [comment]
👋 @damianz5 

⚠️ It will introduce a lot of noise:
image
Solution:
```"selectors_exclude":[".code"]```

I would recommend to use something like
```json
  "selectors": {
    "lvl0": "FIXME h1",
    "lvl1": "FIXME h2",
    "lvl2": "FIXME h3",
    "lvl3": "FIXME h4",
    "lvl4": "FIXME h5, FIXME table td:first-of-type",
    "text": "FIXME p, FIXME li, FIXME table td:last-child"
  }
```
or to add a `docSearch-index` class

**Comment by SylvainGuittard** [comment]
Hi @s-pace !
Thanks for the review. 

IMHO, we should index the code blocks, because the documentation on https://doc.ezplatform.com is developer oriented. It would be nice to search for a namespace or a function.

**Comment by s-pace** [comment]
I can merge it but big disclaimer here

**Comment by damianz5** [comment]
I will create a new test instance with this change and we will compare the results

**Comment by s-pace** [comment]
Good idea @damianz5

**Comment by damianz5** [comment]
Results are better with those changes (content of the tables), please merge
ping @SylvainGuittard

**Comment by s-pace** [comment]
👋 @damianz5 cc @SylvainGuittard 

It looks like your selector `lvl0` doesn't match anything. What would like to pick up?

(Deployed and live)

**Pull request merged**
