### PR TITLE
update Pilosa version to 1.3

### PR DESCRIPTION
**Pull request by jaffee**
# Pull request motivation(s)
Updating Pilosa to version 1.3

### What is the current behaviour?
Only has up to 1.2
*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### What is the expected behaviour?
Needs up to 1.3 now that Pilosa released 1.3.

### CODE REVIEW

**Comment by s-pace** [comment]
👋 @jaffee ,

Thank you for the PR.

It seems that the v1.3 is not available yet. Do you have an ETA of the release?

**Comment by jaffee** [comment]
woops, sorry about that, trying to do too much at once. I'm just waiting on a quick review... it'll get merged and deployed this morning.

**Comment by s-pace** [comment]
Ok please ping me on this thread once it is deployed then. Thanks

**Comment by jaffee** [comment]
OK, @s-pace that's deployed. Thanks!

**Comment by s-pace** [comment]
Deployed ✅

**Pull request merged**
