### PR TITLE
Update clarity_design config

### PR DESCRIPTION
**Pull request by Mavericker-1996**
# Pull request motivation(s)

recover sitemap.xml field

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### CODE REVIEW

**Comment by Mavericker-1996** [comment]
Why does nb-hits didn't change when I recovered sitemap.xml? 
Does it update every 24h ?

**Comment by s-pace** [comment]
[`nb_hits` is only updated when we run the crawl on purpose](https://community.algolia.com/docsearch/config-file.html#nb_hits-special). 

https://github.com/algolia/docsearch-configs/commit/55b64ed8e852f1ba89fdc436faa5ff2641eefe51 does it @Mavericker-1996. It grows.

**Comment by Mavericker-1996** [comment]
thx, so next time when I update my website, will it change automatically or should I tell to run the crawl?

**Comment by Mavericker-1996** [comment]
And I  found it missed  several search  results compared to the last update, will it change automatically ?

**Comment by s-pace** [comment]
> `nb_hits` is the number of records that were extracted and indexed by DocSearch. We check this key internally to keep track of any unintended spike or drop that could reveal a misconfiguration.

> nb_hits is updated automatically each time you run DocSearch on your config. If the term is a tty, DocSearch will prompt you before updating the field. To avoid being prompted, set the UPDATE_NB_HITS environment variable to true (to enable) or false (to disable). This variable can be set in the .env file alongside APPLICATION_ID and API_KEY.

> You don't have to edit this field. We're documenting it here in case you were wondering what it's all about.

You do not have to update it yourself except if you have run the crawl on your own. [See here for more informations](https://community.algolia.com/docsearch/run-your-own.html)


> And I found it missed several search results compared to the last update, will it change automatically ?
 Could you [please fill out this template](https://github.com/algolia/docsearch-configs/blob/master/.github/ISSUE_TEMPLATE) in order to let us know which results are missing please?

Thanks

**Comment by Mavericker-1996** [comment]
# Do you want to request a **feature** or report a **bug**?
**bug**

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= "alibaba-inc_clarity_design

## What is the **current** behaviour?

The missed urls are:
- https://at-design.alibaba-inc.com/dev-doc/quick-start
- https://at-design.alibaba-inc.com/dev-doc/i18n

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

## What is the **expected** behaviour?
add these two missed urls

#### What have you tried to solve it?
update sitemap.xml

#### Any quick clues?



### Any other feedback / questions ?

**Pull request merged**
