### PR TITLE
Update pingcap.json

### PR DESCRIPTION
**Pull request by xuechunL**
# Pull request motivation(s)
Polish `start_urls` and `selectors` value, add some items in `stop_urls`.

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### CODE REVIEW

**Comment by xuechunL** [comment]
@s-pace PTAL.

**Comment by s-pace** [comment]
👋 @xuechunL,

Thanks for the PR. I have [updated it and deployed it](
fa8daef). You will need to update your JS snippet as follow:
```js
docsearch({
  apiKey: 'ad5e63b76a221558bdc65ab1abbec7a2',
  indexName: 'pingcap',
  inputSelector: '### REPLACE ME ####',
  algoliaOptions: { 'facetFilters': ["tags:$TAGS"] },
  debug: false // Set debug to true if you want to inspect the dropdown
});
```
- Replace $TAGS with the tags you want to search on. The list of possible tags is hardcoded in the config. So as of today you have: `cn`, `en`.

  For example if you want to refine the search to the tags "cn" just specify: 'facetFilters': ["tags:cn"]

- Please note that we usually [do not feature blog post](https://community.algolia.com/docsearch/who-can-apply.html#the-checklist) but since the content you provide help the community, we will encompass this section from the search.

- There is no need to ping on top of submitting the PR since we will merge it as soon as possible. We have already noticed the pull request. Hope you understand.

Thank you

**Comment by xuechunL** [comment]
Thanks! We have adjusted the JS snippet as you mentioned above.
But we got some issues about the Chinese UTF-8 code.
WX20190328-180121@2x
PTAL @s-pace 🙏

**Comment by s-pace** [comment]
Solved by b5eee47

**Comment by xuechunL** [comment]
Thanks a lot! 👍 
BTW, We have decided not to support blog search for the time being, so I will create another PR to modify this part.

**Comment by s-pace** [comment]
👋 @xuechunL solved by f6fa771

Could you let us know why you you do not want to support search on this section?

**Comment by xuechunL** [comment]
Sorry to bother, why the Chinese code issue has appeared again? @s-pace PTAL.

**Comment by xuechunL** [comment]
WX20190328-202326@2x

**Comment by xuechunL** [comment]
Maybe we could change the `selectors` config like this?
```
      "lvl0": ".content h1",
      "lvl1": ".content h2",
      "lvl2": ".content h3",
      "lvl3": ".content h4",
      "lvl4": ".content h5",
      "text": ".content p, .content li, .content table, .content pre, .content code"
```

**Comment by s-pace** [comment]
I have just triggered a crawl from an outdate configuration, this issue should be solve right now.

**Comment by xuechunL** [comment]
It works, thank u very much! 👍

**Comment by s-pace** [comment]
Glad to help :)

**Pull request merged**
