### PR TITLE
Update URLs for Tailwind docs

### PR DESCRIPTION
**Pull request by adamwathan**
I'm not totally sure if this is what's necessary, but I recently moved the beta docs (at the "next" subdomain) to our bare domain and would love if the search result links would be updated so they stop going to the next URL 👍🏻

Thanks!

### CODE REVIEW

**Comment by s-pace** [comment]
No need :) https://github.com/algolia/docsearch-configs/commit/d199da849dd47399f4f55c381a53325ad7d68fda

**Comment by adamwathan** [comment]
Hey @s-pace thanks! It looks like search results are still going to the wrong URL though, is that just a matter of time?

**Comment by adamwathan** [comment]
Just to be clear the URLs in this config file need to be change still I think:

https://github.com/algolia/docsearch-configs/blob/master/configs/tailwindcss.json

We no longer have a "next.tailwindcss.com" site, that's just "tailwindcss.com" now, and what used to be "tailwindcss.com" is now "v0.tailwindcss.com" 👍

**Comment by adamwathan** [comment]
Thank you! 🙌🏻

**Pull request merged**
