### PR TITLE
te3201_2019.json: add a level0 selector for 'Admin Info'

### PR DESCRIPTION
**Pull request by damithc**
Following from [this comment](https://github.com/algolia/docsearch-configs/pull/775#issuecomment-473192414), I'm trying to divide the search results into three sections. @s-pace would this work too? If not, I'll try adding a hidden element to relevant pages as suggested.

### CODE REVIEW

**Comment by s-pace** [comment]
@damithc This will work but it will not scale if you want to add further sections. It might end with a long configuration then.

**Comment by damithc** [comment]
> @damithc This will work but it will not scale if you want to add further sections. It might end with a long configuration then.

Understood. Thanks @s-pace 
Shall we go with this approach for the time being? The reason: at the moment our website building tool is not optimized for adding hidden elements to a group of files.

**Comment by s-pace** [comment]
👋 @damithc makes sense. Deployed.

**Comment by damithc** [comment]
Works! Thanks @s-pace

**Pull request merged**
