### PR TITLE
fix(update-commerce.js)

### PR DESCRIPTION
**Pull request by jaepass**
Hi @shortcuts thanks for the help on previous PRs! I've made a fix to the level 0 heading as that is being pull from the nav headings where I've applied an active state. It is currently not in production so I'm not sure how best to test, and hoping it might work as expected. I can provide some code snippets and screenshots. Thanks again!

### CODE REVIEW

**Comment by shortcuts** [comment]
Hey @jaepass, as long as the active class is applied based on the route/path and not a user interaction, it's all good! 
Feel free to let me know once it's in production so we can merge the PR (a crawl will be triggered right after)

**Comment by jaepass** [comment]
Heyhey thank you, yes the active class is based on the route path! Awesome I'll put up the active logic up to production. Thanks for your help again!

**Comment by ScopeyNZ** [comment]
Just FYI @shortcuts we've got some undeployed changes that these selectors are based on.

**Comment by jaepass** [comment]
Hii @shortcuts the changes are pushed to prod on our end so all good to merge this whenever you have a chance, thanks a bunch!

**Pull request merged**
