### PR TITLE
nus-cs2103-ay1920s1.json: capture headings

### PR DESCRIPTION
**Pull request by damithc**
Capture proper headings of schedule pages as they do not contain tabs anymore
Rename documentation -> Other

### CODE REVIEW

**Comment by s-pace** [comment]
Will be deployed within 24h

**Comment by damithc** [comment]
> Will be deployed within 24h

Not deployed yet? 🤔 Or is it a caching problem on my side?

image

**Comment by s-pace** [comment]
Please give it some time. I am off right now, if it is a crawl issue, I will fix it in 3 weeks

**Comment by damithc** [comment]
> Please give it some time. I am off right now, if it is a crawl issue, I will fix it in 3 weeks

No worries @s-pace.  Yes, I suspect it is a crawling issue as my search results still don't match this config file. Let us know when it is fixed. No hurry.

**Pull request merged**
