### PR TITLE
near-sdk-rs docs added to the main index

### PR DESCRIPTION
**Pull request by volovyk-s**
We want to index both https://docs.near.org/ and https://www.near-sdk.io/ on our main documentation website.
The first one is using `Docusaurus` and the second one `Docusaurus 2`. That is why I have added `selectors_key` and some parameters adviced by @shortcuts  (thanks @shortcuts  :)).

### CODE REVIEW

**Review by shortcuts — APPROVED** [review]
looks good!

**Comment by volovyk-s** [comment]
Hey @shortcuts ! This PR was merged > 24 hours ago, but it looks like https://www.near-sdk.io/ is still not indexed. Should I wait for more, or maybe there is some problem in the config?

**Comment by shortcuts** [comment]
Hey, the crawl has been finished 21 hours ago and went well! Keep in mind that the Algolia DocSearch plugin must be enabled in order to use the `contextualSearch` option on Docusaurus

**Comment by volovyk-s** [comment]
@shortcuts all we have for Algolia is here: https://github.com/near/docs/blob/39dd5baf97459b90c9eb3de64578167c1f6f36f3/website/siteConfig.js#L22
Should we change this config somehow?
Or maybe we should change something in`near-sdk.io` repo [here](https://github.com/near/sdk-docs/)?

**Comment by shortcuts** [comment]
Hey @volovyk-s 

I just realized the URL wasn't correct so our scraper ignored it: https://github.com/algolia/docsearch-configs/pull/4580

This should make the SDK searchable!

**Pull request merged**
