### PR TITLE
Update gmapsjs.json

### PR DESCRIPTION
**Pull request by tmentink**
Updated text selector

### CODE REVIEW

**Comment by s-pace** [comment]
LGTM

**Comment by s-pace** [comment]
@tmentink 
I have tailored your config. Triggered the new deployment.
Let me know if it suits you.
NB: Could you add somme special classes to the element matching the lvl0 xpath selector? It will avoid complex expression and allow us to gather records by common section.
Cheers

**Comment by tmentink** [comment]
Hey Sylvian,

I appreciate all your help on this. I just finished updating the html
structure of the sidemenu and submitted a pull request with the new lvl0
selector.

Hope you have a nice thanksgiving!

Thanks again,
Trent

**Comment by s-pace** [comment]
Hey Trent,

You are very welcome.

Hope that you are well too.

Sylvain

**Pull request merged**
