### PR TITLE
update DNS bythebook rollcalldocs

### PR DESCRIPTION
**Pull request by 3CordGuy**
We got a let's encrypt cert for our subdomain.

### CODE REVIEW

**Comment by s-pace** [comment]
👋 @3CordGuy ,
Since you have redirection from URL with or without the las `\`, could you either stop doing client-side rendering or avoid such double redirection? 
```
Getting https://docs.bythebook.com/v15/installing/install-on-a-network/ from selenium
Getting https://docs.bythebook.com/v15/installing/install-on-a-network from selenium
> DocSearch: https://docs.bythebook.com/v15/installing/install-for-use-at-other-locations/ (12 records)
> DocSearch: https://docs.bythebook.com/v15/installing/install-on-a-network/ (38 records)
> DocSearch: https://docs.bythebook.com/v15/installing/install-on-a-network/ (38 records)
```
You will have duplicates otherwise.

Let me know what is your mind about that, I can try to find another dirty solution otherwise.

Cheers

**Comment by 3CordGuy** [comment]
I’m not sure what you mean here. I’m hosting this on Netlify and it is a Gatsby site. Are you talking about the trailing slashes?
There is a post processing that Netlify does by default. I have turned that off. Can you tell if that helps?

Thanks for your help with this!

- Josh

**Comment by s-pace** [comment]
👏 @3CordGuy ,

It works like a charm 👍 

Please share us how did you solve it, this trailing `/` is a redundant issue

Changes deployed,

Thanks you.

**Comment by 3CordGuy** [comment]
Great! Glad to hear that.

In my Netlify settings for the site, I went into *Build & Deploy > Post
Processing* and turned off URL Processing (*Pretty URLS*). Shared
screenshots below.

Hope that helps.

**Pull request merged**
