### PR TITLE
Update timescale config

### PR DESCRIPTION
**Pull request by solugebefola**
# Pull request motivation(s)

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### CODE REVIEW

**Comment by solugebefola** [comment]
@shortcuts not sure why tests failed?

**Comment by shortcuts** [comment]
Hi @solugebefola,

Was the **min_indexed_level** working before? We only accept integers from this key.

So, you should change
https://github.com/algolia/docsearch-configs/blob/e87ab8ff85e10895252bf5bb34963c4432e7bd06/configs/timescale.json#L70-L73

to
```json
"min_indexed_level": 1,
```

**Comment by solugebefola** [comment]
It was working before.  The last time we updated the config was many months ago, so maybe the format changed?  Or the tests were updated?

**Comment by shortcuts** [comment]
@solugebefola It must have been updated.

Looking at your previous records, no errors were detected on your config but it didn't take count of `min_indexed_level` key, from what I'm seeing.

Feel free to @ me if there's any issue with the new configuration, it should be effective in the next 24 hours.

**Pull request merged**
