### PR TITLE
GitLab docs: set "only_content_level": true

### PR DESCRIPTION
**Pull request by ramosmd**
# Pull request motivation(s)

For https://gitlab.com/gitlab-com/gitlab-docs/issues/134

@s-pace does this solve the problem with the description? https://gitlab.com/gitlab-com/gitlab-docs/issues/134

### What is the current behaviour?

Results display headers only, with no content accompanying the hit.

### What is the expected behaviour?

Have a content description accompanying every hit that only shows headers

cc/ @axilleas

### CODE REVIEW

**Comment by ramosmd** [comment]
@s-pace considering that we have a  meta description tag `<meta name="description" content="content">`, how can we change the index to include the description in the search results when available?

**Comment by s-pace** [comment]
This will fix such issue indeed.

`content` here is only a synonym of the `text` attribute.

👏

**Comment by ramosmd** [comment]
Thanks @s-pace! But the DocSearch stopped working 😢 https://docs.gitlab.com/

**Comment by s-pace** [comment]
My bad, I missed a step.

Fixed

**Comment by ramosmd** [comment]
Oh, great, thanks! ❤️

**Pull request merged**
