### PR TITLE
fix: use the lang attribute of <html/>

### PR DESCRIPTION
**Pull request by yuhan0709**
# Pull request motivation(s)

### What is the current behaviour?

The `en-US` and other tags may overlap

### What is the expected behaviour?
use the lang attribute of `<html/>`

### CODE REVIEW

**Review by shortcuts — APPROVED** [review]
Looks good!

**Comment by yuhan0709** [comment]
It's very collapsed, but it still doesn't work. The result is empty :(

**Comment by yuhan0709** [comment]
I want to know if the facet I added takes effect, does the crawler really get the data corresponding to the tag?

**Comment by shortcuts** [comment]
Your website requires client-side rendering, fixed it here: https://github.com/algolia/docsearch-configs/pull/4878

**Pull request merged**
