### PR TITLE
Change URL to live site 

### PR DESCRIPTION
**Pull request by HDinger**
We went live with our page, and would like to update the configuration accordingly.

Best,
Henriette from OpenProject

### CODE REVIEW

**Comment by s-pace** [comment]
@HDinger the crawl fail because of wrong redirections. Could you make sure that the http pages redirect to the https version of the same page **without the port**.

For example, we get the following 301 redirection:

http**s**://docs.openproject.org/development => http://docs.openproject.org/development/ => https://docs.openproject.org:443/development/

Please mind the protocol (http or https) and the missing trailing slash.

Could you redirect the pages this way instead please:

https://docs.openproject.org/development => https://docs.openproject.org/development/

Your search experience will note be updated in the meantime.

Let us know,

**Comment by s-pace** [comment]
The main issue is that the location header of the redirection from the http to https contains the port from the URL

`Redirecting (301) to <GET https://docs.openproject.org:443/enterprise-edition-guide/> from <GET http://docs.openproject.org/enterprise-edition-guide/`

**Comment by machisuji** [comment]
@s-pace May I ask why http as opposed to https is used to begin with? Is it something we do wrong? We're using an AWS load balancer who automatically inserts the :443 into the redirect from http to https. Looking into changing that.

**Comment by machisuji** [comment]
@s-pace This was an issue in our proxy configuration. It is now fixed. Could we please change the URL to the live site again?

**Comment by s-pace** [comment]
@machisuji @HDinger  thanks for the updates. You should be ready to go. You can try it out live 
https://docs.openproject.org/

I have tailored it a bit to make sure the experience is smooth without empty lvl0.

**Comment by HDinger** [comment]
@s-pace Thank you very much for your time and quick responses!

**Pull request merged**
