### PR TITLE
Update liveperson.json

### PR DESCRIPTION
**Pull request by EdenKupe**
# Pull request motivation(s)

New CSS structure in place, updating to fit.

### What is the current behaviour?

SidebarTitle was used, is now gone so moved xpath to select breadcrumbs like lvl0 and lvl1. Did the same for lvl3 to make sure it is consistent, also goes to breadcrumbs now.

CSS class for content also changed so I updated to reflect.

### What is the expected behaviour?

Crawler should use the new selectors to populate the levels.

### CODE REVIEW

**Comment by EdenKupe** [comment]
Hey @s-pace ! Thanks for merging :) I'm still not seeing the changes; has the crawler run yet with the new specifications? Anything further I need to do to make sure the UI reflects the new entries?

Thanks!

**Comment by EdenKupe** [comment]
Got it! Will ping you once the new site goes live! Appreciate it :)

**Comment by EdenKupe** [comment]
Hey @s-pace ! I'm unable to tag the team (because it's private, I think) but in any case, the site is live! If you could trigger the crawler that would be great :)

**Comment by s-pace** [comment]
Right, you were our beta tester for this handle. I was not totally such either it was only internal within the team.
Crawling is currently on going.

**Pull request merged**
