### PR TITLE
Update the page rank

### PR DESCRIPTION
**Pull request by YiniXu9506**
# Pull request motivation(s)
Update the page rank. 

### What is the current behaviour?
The order of version is not we expected.

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### What is the expected behaviour?
The order of return version should be v3.0, v2.1 and then dev.

##### NB2: Any other feedback / questions ?
@s-pace PTAL. Thanks

### CODE REVIEW

**Comment by YiniXu9506** [comment]
@s-pace Conflicts removed! Thank you!

**Comment by YiniXu9506** [comment]
@s-pace If you search query "tidb operator" or "google" or something else, you will see the version `dev` is higher than version `2.1`. However, I set higher value to `v2.1`. I don't know why this happen.

**Comment by s-pace** [comment]
It is not deployed yet

**Comment by s-pace** [comment]
The page_rank is only here to separate hits with same global ranking

**Comment by YiniXu9506** [comment]
@s-pace I believe the global rankings of `dev` and `v2.1` are the same if I don't set any params to them. So I think `v2.1` will be higher than `dev` when I set the higher value to `v2.1`.

It seems most return results are ordered by 3.0, 2.1 and then dev.  But some of them are not, `dev` still higher than `v2.0`.

**Comment by s-pace** [comment]
This ranking is only effective when the global one is a tie. This PR ia not deployed yet. Let’s see it tomorrow. I will show you the ranking for a specific query once it is deployed. Let me know the query you want to check

**Comment by YiniXu9506** [comment]
Got it. Would you please help me to check "tidb operator". Please let me know once it deployed. Thank you so much!

**Comment by s-pace** [comment]
We will

**Comment by s-pace** [comment]
Deployed. Is it better now?

**Comment by YiniXu9506** [comment]
I am sorry, I still get `dev` before `v2.1` from the results if I search query `tidb operator` or `google`.

**Comment by s-pace** [comment]
Are you sure? I have tried with these queries on https://pingcap.com/en/ and v3 was first

**Comment by s-pace** [comment]
Dev is before v2 but with hits that are not the same

**Comment by s-pace** [comment]
Page_rank is only useful when there is a tie

**Comment by YiniXu9506** [comment]
Okay I see what you mean! Thanks @s-pace

Sylvain Pace <notifications@github.com>于2019年8月7日 周三下午7:32写道：

**Pull request merged**
