### PR TITLE
Increased page ranking for the /Security-Solace.htm page

### PR DESCRIPTION
**Pull request by ArshRai17**
# Pull request motivation(s)

Hi Clement / @shortcuts , I made an update earlier (#3207 ) to increase the page ranking for our [Security Overview](https://docs.solace.com/Security/Security-Solace.htm) page, but I see no difference.  I am trying something else here. 

Also, after the #3034  update, the page does not even display in the search results anymore.

### What is the current behaviour?
The [Security Overview](https://docs.solace.com/Security/Security-Solace.htm) page does not display in search results.

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

1. Type "security" (with or without the quotes)
2. The [Security Overview](https://github.com/algolia/docsearch-configs/pull/3034) page does not display in the search result. This behaviour started after the #3034  update.

### What is the expected behaviour?
We want this page to ranked highest when searching for the term "security". https://docs.solace.com/Security/Security-Solace.htm

##### NB: Do you want to request a **feature** or report a **bug**?
bug

##### NB2: Any other feedback / questions ?
Again, an easier way to quickly test the updates would be great!

### CODE REVIEW

**Comment by shortcuts** [comment]
Hi,

As you can see on the screenshot below, the `Security Overview` page is returned first even after the query `se`, the issue should be related to some client-side rendering because other levels are not found.
Screenshot 2021-01-12 at 09 30 50

I'll try to make it work later today and let you know.

Also, you can [run the crawler on your own](https://docsearch.algolia.com/docs/run-your-own/#running-the-crawler-from-the-code-base) to try your results before submitting the PR if you want.

Have a nice day.

**Comment by shortcuts** [comment]
@ArshRai17 should we scrape this endpoint? https://docs.solace.com/API-Developer-Online-Ref-Documentation/jms/com/solacesystems/common It's not stated in your `start_urls` or `stop_urls` which leads to a lot of unwanted requests.

**Comment by shortcuts** [comment]
Everything should be fixed in https://github.com/algolia/docsearch-configs/pull/3221/commits/30b8c97a0541646bcc9cdc790823cd33690177b5, the client-side rendering added 30k+ hits.

Let me know if you can see the changes in the next 24 hours,
Have a nice day.

**Comment by ArshRai17** [comment]
> Everything should be fixed in [30b8c97](https://github.com/algolia/docsearch-configs/commit/30b8c97a0541646bcc9cdc790823cd33690177b5), the client-side rendering added 30k+ hits.
> 
> Let me know if you can see the changes in the next 24 hours,
> Have a nice day.

@shortcuts thanks for the updates. I still don't see the Security Overview page in the search results, but I will wait for 24 hrs for the changes. Our field team has raised a few tickets as they are not able to find the page using our search, so it's urgent to get it fixed. Thank you for your help, I appreciate it!

**Comment by ArshRai17** [comment]
> @ArshRai17 should we scrape this endpoint? https://docs.solace.com/API-Developer-Online-Ref-Documentation/jms/com/solacesystems/common It's not stated in your `start_urls` or `stop_urls` which leads to a lot of unwanted requests.

We've been requested to make items in this endpoint searchable; t's mostly CLI and event references. It does add some noise, but it's a request from our user to keep it. So, we will leave it for now.

**Comment by shortcuts** [comment]
@ArshRai17 It looks like the crawl has been stalled a few minutes ago and stopped mid-way, I'll see what could be the issue and let you know ASAP.

**Comment by ArshRai17** [comment]
> @ArshRai17 It looks like the crawl has been stalled a few minutes ago and stopped mid-way, I'll see what could be the issue and let you know ASAP.

@shortcuts Unfortunately, The [Security Overview](https://docs.solace.com/Security/Security-Solace.htm) page still does not display in search; instead, the [MQTT Security](https://docs.solace.com/MQTT-311-Prtl-Conformance-Spec/Security.htm#_Toc430864975) is on the top, which we do not want. 
![image](https://user-images.githubusercontent.com/29955404/104469565-a65ca480-5586-11eb-9e07-94e02d399c30.png.

**Comment by shortcuts** [comment]
@ArshRai17  Fixed. You should see the update ASAP!

**Comment by ArshRai17** [comment]
> ~@ArshRai17 Fixed. You should see the update ASAP!~
> 
> `Security Overview` page have such few matches on word `security` that even after a ranking of `110` it comes at place 10.
> 
> I've updated it with a rank of `200`.

@shortcuts , you are the man! Thank you so much for your help.

It's strange that the Security Overview page does not match the term "security" itself. We've been diligent with the headings and keywords in the docs. Is there anything I can do to improve these issues in our docs? All the same, thanks again!

**Comment by shortcuts** [comment]
I think using the `lvl0` selectors could change the results a lot, as the `selector level` gives weight to a result. It looks like results in the `MQTT` page where on `lvl1-lvl2` which gives more weight than results in the `lvl1-lvl3` for the `Security Overview` page!

Glad it now works,
Have a nice day.

**Pull request merged**
