### PR TITLE
Improve Material-UI configuration

### PR DESCRIPTION
**Pull request by mnajdova**
# Pull request motivation(s)

The intent is to cover the v4 version documentation in the search.

### CODE REVIEW

**Comment by shortcuts** [comment]
Hey @mnajdova,

Please let me know when the v4 has been deployed, I will merge this PR right after as it will trigger a new crawl.

**Comment by shortcuts** [comment]
(and congrats on the release :))

**Comment by mnajdova** [comment]
> (and congrats on the release :))

Thanks 🙏

**Comment by mnajdova** [comment]
@shortcuts https://v4.material-ui.com/ is deployed :)

**Comment by shortcuts** [comment]
> @shortcuts https://v4.material-ui.com/ is deployed :)

Congrats!!

**Pull request merged**
