### PR TITLE
Update Commerce.js config

### PR DESCRIPTION
**Pull request by jaepass**
Update heading level configuration in Commerce.js

### CODE REVIEW

**Comment by shortcuts** [comment]
hi @jaepass, some selectors were not working properly, this fix should match what you want!

feel free to let me know if it's not the case

**Comment by jaepass** [comment]
heeyhey @shortcuts thanks for the merge and fix, I'm currently testing it and suggestions for headings aren't coming out correctly. I'll have a look and put up another pr. thanks again!

**Comment by shortcuts** [comment]
@jaepass Sure, feel free to @ me if you need some help!

**Comment by jaepass** [comment]
Awesome will do thank you!

**Pull request merged**
