### PR TITLE
update mdanalysis.org search config

### PR DESCRIPTION
**Pull request by orbeckst**
# Pull request motivation(s)

Improve the relevance of the index for the site https://www.mdanalysis.org

- do not index development docs (https://www.mdanalysis.org/mdanalysis) or paginated blog
- use sitemap (probably now needed to find all blog posts now that pagination has been removed); however, the sitemap currently only includes the content generated by jekyll (using the jekyll-sitemap plugin), not the sub-sites that are accessible by crawling. I am reading the ["How it works" docs](https://community.algolia.com/docsearch/documentation/docsearch-scraper/config-options/) as if Algolia will crawl starting from the pages in the sitemap so I hope this will still index most of our site.
- closes MDAnalysis/MDAnalysis.github.io#77

### What is the current behaviour?

Content shows up duplicated or near duplicated (and the [Recommendations](https://community.algolia.com/docsearch/documentation/docsearch/recommendations/) rightly advise against such duplication).

### What is the expected behaviour?
Users only expect to see a single relevant topic of the same name.

##### NB: Do you want to request a **feature** or report a **bug**?
Update to our indexer config.

##### NB2: Any other feedback / questions ?
We now provide a sitemap.xml and we hope that the indexer will simply start crawling from there. If not then we have to come up with additional ways to create more sitemaps.

### CODE REVIEW

**Comment by maxiloc** [comment]
Thanks. I'll deploy right away

**Comment by orbeckst** [comment]
Thanks @maxiloc – I assume I can expect to see changes after ~24h when your index has been rebuilt?

**Comment by maxiloc** [comment]
I deployed it manually, so it launch a reindex at the same time.
Should be live now

**Comment by orbeckst** [comment]
Yes, just checked again and it looks as if the changes took place. Thanks again!

**Pull request merged**
