### PR TITLE
Use https for Jest

### PR DESCRIPTION
**Pull request by JoelMarcey**

### CODE REVIEW

**Comment by JoelMarcey** [comment]
Fixes https://github.com/facebook/jest/issues/5360

**Comment by s-pace** [comment]
👌 

Updated, deployed and already live.

Feel free to give us feedback.

The localisation feature is ready too (thanks to facet)

**Comment by JoelMarcey** [comment]
@s-pace Thanks!

Is there a PR for the localization work?

**Comment by s-pace** [comment]
Hey @JoelMarcey ,

We don't have a particular PR for this feature since it uses our facet feature and it is available since quite a while.

You can [have a look here](https://github.com/algolia/docsearch-configs/pull/292)

Feel free to ask us for any other point to highlight.

**Pull request merged**
