### PR TITLE
add blog config json

### PR DESCRIPTION
**Pull request by WinmezzZ**
# Pull request motivation(s)

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### CODE REVIEW

**Comment by WinmezzZ** [comment]
Hello there, what's the meaning with `application not verified`? What should I do? I'm first time to using doc-search of algolia, thanks.

**Comment by shortcuts** [comment]
Hey @WinmezzZ, it means that you've not (yet) applied to DocSearch via: https://docsearch.algolia.com/apply

**Comment by WinmezzZ** [comment]
> Hey @WinmezzZ, it means that you've not (yet) applied to DocSearch via: https://docsearch.algolia.com/apply

I've already applied and registered for the application and index.

Just now, I applied it again.

**Comment by shortcuts** [comment]
Got it, you should have details via email soon

**Comment by shortcuts** [comment]
Closing since the app is now deployed

**Pull request closed without merging**
