### PR TITLE
Update wix.json

### PR DESCRIPTION
**Pull request by kupriyanenko**
Library has changed name and site URL. Now it called Playable.

### CODE REVIEW

**Comment by s-pace** [comment]
Changing the index name will change the key, please submit a new configuration file (I will remove the old one) or keep the index name pls.

**Comment by kupriyanenko** [comment]
@s-pace in my PR I already removed old one and created new one `configs/wix.json → configs/wix_playable.json`, should I keep old config and just add new one?

**Comment by s-pace** [comment]
My bad, I will merge it and provide your new key

**Comment by s-pace** [comment]
👍 new key : 16e486e2b40c2263303630cc39f2510a
 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" /> 
 
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script> 
<script type="text/javascript"> docsearch({ 
 apiKey: '16e486e2b40c2263303630cc39f2510a', 
 indexName: 'wix_playable', 
 inputSelector: '### REPLACE ME ####', 
 debug: false // Set debug to true if you want to inspect the dropdown 
}); 
</script>

**Pull request merged**
