### PR TITLE
Create for bootstrap-vue.ru

### PR DESCRIPTION
**Pull request by Hkr32**
I have submitted an application for approval

### CODE REVIEW

**Comment by shortcuts** [comment]
Closing since applications have been answered/deployed

**Comment by Hkr32** [comment]
Did I do something wrong?

**Comment by shortcuts** [comment]
Hey, looking at the email, the conversation have been marked as inactive since we did not receive confirmation from you in the last 15 days

**Comment by Hkr32** [comment]
image

**Comment by Hkr32** [comment]
What should I do next? I replied to your letter back in November.

**Comment by shortcuts** [comment]
Hey, we are doing some work on our infra but will come back to you at most **next week**

Sorry for the outage :D

**Comment by Hkr32** [comment]
I'm still waiting...

**Comment by shortcuts** [comment]
Hey @Hkr32, have you reapplied since last time? I can't see any other ticket that the one we discussed above

**Comment by Hkr32** [comment]
I didn't apply, but I will now. Thank you. I just didn't know it was possible)

**Comment by shortcuts** [comment]
Yes please do so https://docsearch.algolia.com/apply/

**Pull request closed without merging**
