### PR TITLE
Adding jekyll-algolia

### PR DESCRIPTION
**Pull request by pixelastic**

### CODE REVIEW

**Comment by pixelastic** [comment]
@s-pace Could you have a look and let me know if it looks good to you?

Also, I don't remember the next steps. Should I run `./docsearch deploy:config` once this is merged to deploy it to the crawler?

**Comment by maxiloc** [comment]
Let me double check it and deploy

**Comment by maxiloc** [comment]
All good, here is the key => 5e2de32b362723ffdb03414c5c3d2ec8

**Comment by pixelastic** [comment]
Thanks!

**Pull request merged**
