### PR TITLE
Add apache-spark versions 3.1.0 and 3.1.1

### PR DESCRIPTION
**Pull request by gengliangwang**
# Pull request motivation(s)
As the apache spark community are going to release 3.1.1, we should add versions for Spark documentation of different releases. 

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### What is the expected behaviour?

Supporting version key filtering in https://spark.apache.org/docs

### CODE REVIEW

**Comment by gengliangwang** [comment]
cc @shortcuts

**Comment by gengliangwang** [comment]
https://github.com/apache/spark/pull/31525

Hi @shortcuts, I have changed the version to 3.1.1 already, and we are going to release the new documentation site https://spark.apache.org/docs/3.1.1 soon. 
Quick question: how long does it take for the Docsearch to become working after the new site is available?

**Comment by shortcuts** [comment]
Hi @gengliangwang,

The crawl has been done right after the merge, so the next crawl should be in ~22 hours.

If it can't wait until then, let me know once it's released!

**Comment by gengliangwang** [comment]
Hi @shortcuts , the Spark 3.1.1 docs is now available:
https://spark.apache.org/docs/3.1.1/sql-ref.html
Could you help trigger the crawl?

**Comment by shortcuts** [comment]
Hey, I'm not sure why the `3.1.1` didn't get caught on last crawl, a new one has been started, it should be good right after it!

I've also removed the `3.1.0` as it doesn't exists on your website https://github.com/algolia/docsearch-configs/pull/3679.

**Comment by gengliangwang** [comment]
Hi, @shortcuts I just tried it and it works now.
One quick comment, the search result always comes with a ending `#content`. Is it possible that we can remove it?

**Pull request merged**
