### PR TITLE
Update nervos_ckbd.json

### PR DESCRIPTION
**Pull request by xxuejie**
# Pull request motivation(s)

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### CODE REVIEW

**Comment by s-pace** [comment]
image
@xxuejie the domain is still not ready since there is still a `301` redirecting to the `docs-new` website. Can you please make sure this is ready and then submit a PR?

The crawl is frozen in the meantime

**Comment by xxuejie** [comment]
@s-pace Hi there, we've fixed the config on our side, the new config file shall be exactly what is contained in this PR, could you help us re-enable the crawl? Many thanks!

**Comment by s-pace** [comment]
@xxuejie Crawl done and the new domain is well configured. You can check it ou on your website :)

**Comment by xxuejie** [comment]
@s-pace Many thanks!

**Pull request merged**
