### PR TITLE
Update v-play.json config

### PR DESCRIPTION
**Pull request by alexhvplay**
Update config with start urls of component overview pages and sitemap files for V-Play and Qt components.

# Pull request motivation(s)
Improve search results returned by doc search.

### What is the current behaviour?
Current crawl coverage missing key pages of our documentation. This was tested by an Algolia engineer, by adding one example page as start_url, which then showed up in search results as expected.

### What is the expected behaviour?
Important pages should show up in search results, especially when there is a 1to1 string match on the page h1 tag.

### CODE REVIEW

**Comment by s-pace** [comment]
Could you add a `.toc`clas to the big `<ul/>` element [available on this page](https://v-play.net/doc/qt/hierarchy/qsignalmapper/) please?
We do not want to extract this list (`selectors_exclude`). It is too big to be correctly indexed. Furthermore it is only a list of links, it creates an unnecessary step to reach the valuable information.

Please let me know once this is live.

**Comment by alexhvplay** [comment]
Hi, thank you for the quick feedback.
Would it also be possible to add this url as stop_urls, or add another exclude selector that points to this specific list, like "#doc-content.qt_inheritancehierarchy-index .doc-page ul"? This would be easier than modifying this specific page source.

**Comment by s-pace** [comment]
Hi @alexhvplay,

Using the specific `selectors_exclude` is better since adding this link to `stop_urls` will avoid to browse links from this page.

I have added it and launched a new crawl, we are receiving a lot of 500 errors. Could you have a look please?
```
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-itemviews-customsortfiltermodel-customsortfiltermodel-qrc/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-painting-basicdrawing-window-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-painting-basicdrawing-renderarea-h/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-mainwindows-dockwidgets-mainwindow-h/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-painting-basicdrawing-basicdrawing-pro/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-mainwindows-dockwidgets-main-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-painting-basicdrawing-renderarea-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-painting-basicdrawing-main-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-mainwindows-dockwidgets-dockwidgets-pro/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-widgets-imageviewer-main-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-widgets-imageviewer-imageviewer-h/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtquick-touchinteraction-multipointtouch-multiflame-qml/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtquick-touchinteraction-multipointtouch-content-augmentedtouchpoint-qml/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtquick-touchinteraction-touchinteraction-qrc/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtquick-touchinteraction-touchinteraction-pro/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtquick-touchinteraction-touchinteraction-qmlproject/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-widgets-imageviewer-imageviewer-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtquick-touchinteraction-main-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:58 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtdesigner-taskmenuextension-tictactoetaskmenu-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtdesigner-taskmenuextension-tictactoe-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-itemviews-editabletreemodel-mainwindow-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-itemviews-editabletreemodel-editabletreemodel-qrc/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-itemviews-editabletreemodel-treeitem-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-itemviews-editabletreemodel-treemodel-h/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-itemviews-editabletreemodel-main-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qml-qt-labs-platform-menu-members/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-itemviews-editabletreemodel-mainwindow-ui/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-itemviews-editabletreemodel-editabletreemodel-pro/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtcharts-barmodelmapper-tablewidget-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtcharts-barmodelmapper-customtablemodel-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qml-qtquick-controls2-abstractbutton-members/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtcharts-barmodelmapper-main-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtcharts-barmodelmapper-tablewidget-h/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtcharts-barmodelmapper-barmodelmapper-pro/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtcharts-barmodelmapper-customtablemodel-h/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:38:59 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-draganddrop-dropsite-dropsite-pro/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:39:00 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtcharts-zoomlinechart-zoomlinechart-pro/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:39:00 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtcharts-zoomlinechart-main-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:39:00 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-draganddrop-dropsite-droparea-h/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:39:00 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-draganddrop-dropsite-dropsitewindow-cpp/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:39:00 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtcharts-zoomlinechart-chartview-h/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:39:00 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtextbrowser-members/> (failed 1 times): 500 Internal Server Error
2019-02-05 15:39:00 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://v-play.net/doc/qt/qtwidgets-draganddrop-dropsite-droparea-cpp/> (failed 1 times): 500 Internal Server Error
```

**Comment by alexhvplay** [comment]
Hi @s-pace ,
all the shown pages are actually reachable, it looks like the web server is maybe limiting your crawler, causing requests to fail somewhere in the middle of the https://v-play.net/sitemap_vpdocsqt.xml sitemap. Is there a possibility to configure a timeout for the crawl speed, of run the crawl in batches?

**Comment by s-pace** [comment]
No, it is not. Could you allow a specific `user_agent`?

**Comment by alexhvplay** [comment]
I will check back with our server administrator, thank you very much for the help so far!

**Comment by alexhvplay** [comment]
We are still struggling a bit to track down the exact issue. How many parallel processes is your crawler using, is there any estimation of requests per second that are made by the crawler? We suspect that our web server might actually run out of PHP processes to handle all the requests.

**Comment by s-pace** [comment]
Our crawler is not currently running with this new configuration.
We can add a specific `user_agent` to the configuration to let you spot it
Let me know if I should run trigger one crawl right now

**Comment by s-pace** [comment]
For your configuration, we only have one crawl at the same time.

**Comment by s-pace** [comment]
Right now the request we are doing is ~25/s

**Comment by s-pace** [comment]
@alexhvplay any more details required from your end?

Let us know

**Comment by s-pace** [comment]
Closing since we haven't received any reply from your side @alexhvplay . Please feel free to reopen it

**Pull request closed without merging**
