### PR TITLE
Add /kata, /stats, and /podcasts in coderdojo.json

### PR DESCRIPTION
**Pull request by yasulab**
# Pull request motivation(s)

Hi! Thanks for supporting [:octocat: coderdojo-japan/coderdojo.jp](https://github.com/coderdojo-japan/coderdojo.jp) website via [DocSearch program](https://www.algolia.com/for-open-source/). 😆

I am [owner of the website](https://github.com/coderdojo-japan/coderdojo.jp/graphs/contributors). Based on requests from our visitors we would like to add a wiki page ([/kata](https://coderdojo.jp/kata)), stats page ([/stats](https://coderdojo.jp/stats)), and podcasting page ([/podcasts](https://coderdojo.jp/podcasts)) to `start_urls` in `coderdojo.json` to be indexed. 🔍 

In order to provide better Algolia search UX with our visitors, hope you consider merging this PR. 

### What is the current behaviour?

* Only pages under [/docs](https://coderdojo.jp/docs) are searchable but our visitors often expect search results to include a wiki page ([/kata](https://coderdojo.jp/kata)), stats page ([/stats](https://coderdojo.jp/stats)), and podcasting page ([/podcasts](https://coderdojo.jp/podcasts)).

### What is the expected behaviour?

* I would like to index the pages above in addition to existing URL ([/docs](https://coderdojo.jp/docs)) so that our visitors can find out information they want before contacting us by emails.

### CODE REVIEW

**Review by shortcuts — CHANGES_REQUESTED** [review]
Thanks for the PR.

You can remove [this option](https://github.com/algolia/docsearch-configs/pull/4043/files#diff-78f0a9ea65773be33de0d71bb6291ae5eab892a5c97c0a4d546eb4e114716367R22) in order to make the content from `/kata` available

**Comment by shortcuts** [comment]
Thanks for the update @yasulab.

What I was suggesting is: to keep the `start_urls` [as you previously added it](https://github.com/algolia/docsearch-configs/pull/4043/commits/ddadd4e83f4fd7fb060cf219877e51702f3ce806#diff-78f0a9ea65773be33de0d71bb6291ae5eab892a5c97c0a4d546eb4e114716367R4-R7) but remove the [`scrape_start_urls`](https://github.com/algolia/docsearch-configs/blob/a827bc1bb669cb52eb52741a43676b98172d85cf/configs/coderdojo.json#L16) option.

**Comment by yasulab** [comment]
@shortcuts Thanks for your comment! I have changed and checked CI passed. :eyes: ✅ 

Do I need to squash? Let me know if anything needed to do in my side. 😉

**Comment by shortcuts** [comment]
All good @yasulab! Thanks :D 

You'll see the changes in the next 24 hours

**Comment by yasulab** [comment]
Thanks for merging this PR! 😆✨ And I have confirmed that the DocSearch in [our website](https://coderdojo.jp) provides better results in Japanese! 😎🆒✨

CoderDojo_Search

**Comment by shortcuts** [comment]
Glad to hear that @yasulab! Enjoy

**Pull request merged**
