### PR TITLE
edit routes for rasa config

### PR DESCRIPTION
**Pull request by amn41**
- WIP
- we are bringing new documentation live tomorrow
- want to make sure this is up-to-date and everything gets re-indexed 
- currently updating the sitemap, will share URLs here if that helps

### CODE REVIEW

**Comment by s-pace** [comment]
LGTM

**Comment by amn41** [comment]
thanks @s-pace ! site is live so please re-index ASAP :)

**Comment by s-pace** [comment]
Done @amn41

**Comment by amn41** [comment]
thank you! works perfectly!

**Comment by amn41** [comment]
@s-pace any idea why the pages under rasa.com/docs/rasa are not getting indexed?

the home page rasa.com/docs has links to getting-started, rasa, and rasa-x, but only getting search results for rasa-x part.

**Comment by s-pace** [comment]
👋 @amn41 

We are crawling the following pages:

```
> DocSearch: http://rasa.com/docs/ 7 records)
> DocSearch: http://rasa.com/docs/rasa-x/ 11 records)
> DocSearch: http://rasa.com/docs/getting-started/ 41 records)
> DocSearch: http://rasa.com/docs/rasa-x/api/rasa-x-http-api/ 1 records)
> DocSearch: http://rasa.com/docs/rasa-x/manage-models/ 4 records)
> DocSearch: http://rasa.com/docs/rasa-x/enterprise/openshift-kubernetes/ 64 records)
> DocSearch: http://rasa.com/docs/rasa-x/enterprise/single-sign-on/ 15 records)
> DocSearch: http://rasa.com/docs/rasa-x/annotate-conversations/ 3 records)
> DocSearch: http://rasa.com/docs/rasa-x/enterprise/role-based-access-control/ 10 records)
> DocSearch: http://rasa.com/docs/rasa-x/get-feedback-from-test-users/ 17 records)
> DocSearch: http://rasa.com/docs/rasa-x/deploy/ 90 records)
> DocSearch: http://rasa.com/docs/rasa-x/installation-and-setup/ 9 records)
> DocSearch: http://rasa.com/docs/rasa-x/import-conversations/ 31 records)
> DocSearch: http://rasa.com/docs/rasa-x/enterprise/deployment-environments/
```
Which one are you missing? Could you provide us a [compliant sitemap](https://community.algolia.com/docsearch/tips.html#use-a-sitemapxml) please?

Cheers

**Comment by amn41** [comment]
Thanks @s-pace ! sorry I hadn't seen you'd replied here. 

Sitemap is here: https://rasa.com/docs/sitemap.xml 

So what's missing is all the pages under /docs/rasa/

**Comment by amn41** [comment]
is that sitemap OK? are those pages getting crawled now ?

**Comment by s-pace** [comment]
I do not think that your sitemap is correctly set. sitemap.org

**Pull request merged**
