### PR TITLE
Force sitemap url crawling

### PR DESCRIPTION
**Pull request by solugebefola**
# Pull request motivation(s)

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### CODE REVIEW

**Comment by s-pace** [comment]
👋 @solugebefola 

Please use the issue's template correctly, we would not be able to clearly help you otherwise.

Cheers

**Comment by solugebefola** [comment]
### Pull request motivation(s)
#### What is the current behaviour?
The search functionality does not catch many of the pages on the site.  Example: searching for "indexing" does not return the page http://docs-exp.timescale.com/v0.10/using-timescaledb/schema-management#indexing.  This seems to be a problem with many of the pages on the site. 

I suspect that this is due to the crawler not rendering pages properly (They are built with react, and the way they are built may be incompatible with selenium?), but honestly, I don't have any evidence that suggests a cause.  I thought that forcing a crawl using the sitemap might work.

### What is the expected behaviour?
NB: Do you want to request a feature or report a bug?
NB2: Any other feedback / questions ?

**Comment by solugebefola** [comment]
Here is a screenshot example. 
screen shot 2018-08-06 at 2 05 31 pm
You can see that I am on a page with "Indexing" in the title, yet a search for "indexing" does not show that page in the results.

**Comment by s-pace** [comment]
Thank your for the details

`force_sitemap_urls_crawling` is here to change the way we handle parsed links from the sitemap. Not helpful here.

I have noticed and send you an email regarding an issue with this page http://docs-exp.timescale.com/v0.5/main that freeze the crawl. Since this webpage is not useful for us (no documentation in it), could you provide us a sitemap without this page? We will then avoid to crawl this exacte page.

Cheers

**Pull request closed without merging**
