### PR TITLE
Tweak config for lightningdesignsystem.com

### PR DESCRIPTION
**Pull request by kaelig**
I'm starting to play around with crawler-specific attributes, let's see what happens :)

### CODE REVIEW

**Comment by maxiloc** [comment]
Scrappy does not handle this syntax for css selector [data-docsearch-ignore], the easiest would be to add a class instead

**Comment by maxiloc** [comment]
I am going to revert that in the meantime

**Comment by kaelig** [comment]
Oh, thanks!

Is this something you plan on supporting?

**Comment by maxiloc** [comment]
This is tricky as this not handle by our code logic but scrappy and lxml which our crawler is built on top of. In the short term I don't think this is something we can handle.

**Comment by kaelig** [comment]
Ok that makes sense, I'll just switch to class names :)

**Pull request merged**
