### PR TITLE
chore(config): update after 3.1 release

### PR DESCRIPTION
**Pull request by thetutlage**

### CODE REVIEW

**Comment by thetutlage** [comment]
Can I have someone look into this

**Comment by maxiloc** [comment]
@thetutlage Sorry for the delay, I already did a fix a few hours ago, but did not see the PR. I'll merge what I did with your work. I'll ping you when it's deployed (next few minutes)

**Comment by thetutlage** [comment]
@maxiloc 👍🏻

**Comment by maxiloc** [comment]
Should be good now

**Comment by ElPicador** [comment]
Closing this

**Pull request closed without merging**
