### PR TITLE
remove rc from glamorous site settings

### PR DESCRIPTION
**Pull request by kentcdodds**
We'll be releasing the site soon!

### CODE REVIEW

**Comment by Haroenv** [comment]
Perfect, will deploy soon

**Comment by kentcdodds** [comment]
Looks like search is busted on [glamorous.rocks](https://glamorous.rocks/) now :-(

Could I get help debugging this?

screen shot 2017-07-29 at 7 15 46 am

**Comment by Haroenv** [comment]
Hmm, seems odd, I’m going to check that right away

**Comment by Haroenv** [comment]
Seems like `rc.` still works, maybe something is stalled on the deployment @kentcdodds

**Comment by kentcdodds** [comment]
How can I help? 😀

**Comment by Haroenv** [comment]
Well I couldn’t test it fully because I don’t have production credentials. What I’m thinking now is that this configuration is actually matching `.glamorous.rocks` instead of `glamorous.rocks`.

**Comment by kentcdodds** [comment]
Who can we get who could help test things out and find out what needs to be changed?

**Pull request merged**
