### PR TITLE
Update Unibeautify with custom domain

### PR DESCRIPTION
**Pull request by Glavin001**
https://unibeautify.com/

### CODE REVIEW

**Comment by s-pace** [comment]
Please try to have a compliant sitemap https://unibeautify.com/sitemap.xml:
[reference}(https://www.sitemaps.org/protocol.html)

**Comment by Glavin001** [comment]
I use https://docusaurus.io/

I think this is the sitemap it generates automatically: https://unibeautify.com/sitemap.xml
Is there something I need to change?

Thanks!

**Comment by s-pace** [comment]
👋 @Glavin001 ,

The sitemap they have is not compliant either. It mus be compliant to the [ref](https://www.sitemaps.org/protocol.html) I have send you.

It isn't a proper XML for now

**Comment by storemey01** [comment]
Hello i am facing same issue for xml. please check below link and help me to solve it

[(https://www.xml-sitemaps.com/validate-xml-sitemap.html?op=validate-xml-sitemap&go=1&sitemapurl=https%3A%2F%2Fwww.storemey.com%2Fsitemap_search.xml&submit=Validate+Sitemap)]

**Pull request merged**
