### PR TITLE
fix(arco): update config

### PR DESCRIPTION
**Pull request by shortcuts**
# Pull request motivation(s)

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### CODE REVIEW

**Comment by yuhan0709** [comment]
still not working😭

**Comment by yuhan0709** [comment]
> still not working😭
add the `['tags:vue']`in facetFilters parameter can't find anything, has the data been crawled?

**Comment by shortcuts** [comment]
Hey, I have a thing to finish first and will help you debut it!

**Comment by shortcuts** [comment]
Hey @yuhan0709, fixed here: https://github.com/algolia/docsearch-configs/pull/4902

Please allow a few hours before seeing the changes, adding delay to client-side rendering make the crawl really slow.

**Pull request merged**
