### PR TITLE
[Issue 2978] Fix search for Apache Pulsar website

### PR DESCRIPTION
**Pull request by Jennifer88huang**
# Pull request motivation(s)
The search still does not work for Pulsar 2.7.0.

### What is the current behaviour?

image

### What is the expected behaviour?
Search should work well for 2.7.0 release.

### CODE REVIEW

**Comment by shortcuts** [comment]
Hi,

Thanks for the PR.

The crawl tasks have been executed without any issues on our side.

It looks like your **latest stable version** (2.7.0 in this case) doesn't exists at the URL pattern defined in your config (e.g.: https://pulsar.apache.org/docs/en/2.7.0/) but https://pulsar.apache.org/docs/en/.

I'll do some tests and update it once it's working!

**Comment by shortcuts** [comment]
@Jennifer88huang after a few tests, it looks like the `version` variable is retrieved without it specifying it and still works as an `attributeForFaceting`

You should be able to see the changes in the next 24 hours.

Hope this solves your issue,
Have a nice day

**Comment by Jennifer88huang** [comment]
@shortcuts Thank you very much for your test and detailed explanation.
Now since you remove the versions, so we do not need to update the config file when we have more releases later. Is it correct?

**Comment by shortcuts** [comment]
You shouldn't (waiting for the crawl to be effective to confirm) need to update it anymore but you can still use them as filters!

**Comment by Jennifer88huang** [comment]
@shortcuts That's great. Will check it after 24 hours. 
Thank you very much for your support and help, and have a nice day~

**Pull request merged**
