### PR TITLE
Change URL to github pages custom domain

### PR DESCRIPTION
**Pull request by oliverguenther**
We updated our github pages to use a custom domain, and would like to update the crawler configuration accordingly.

Best,
Oliver from OpenProject

### CODE REVIEW

**Comment by oliverguenther** [comment]
Hi @s-pace , I updated the sitemap, thanks for the pointer. I'm sorry but I'm not sure I follow regarding your other remark: "avoid having the port part". Avoid using ports in the references within the page? I'm not aware that we do anything special there.

**Comment by s-pace** [comment]
@oliverguenther Thanks for updating the sitemap. It works well.

It works so well that the crawl was browsing the german pages (which are english btw) and the same page with the port number. This behaviour introduces duplicates from the search.

https://github.com/algolia/docsearch-configs/commit/f3ae3914417e56358d25de4ddb335940195a1031 avoid crawling these german pages. If you want to be able to filter on languages, let me know. I will update your configuration accordingly and you will need to update the JS snippet so that it filter on the proper language. It will be similar to this snippet (without the version):
image

> avoid having the port part.

Sorry, it was indeed not that clear! Pages of your websites are available from https://docs.openproject-edge.com:443/guide/enterprise-features/agile-boards/ & https://docs.openproject-edge.com/guide/enterprise-features/agile-boards/.

Could you make sure pages are not available from URL with the port number `:443`? It will help to avoid duplicates from the search. 

Thanks

**Comment by oliverguenther** [comment]
I see, thanks. The site is still being built and translations are not being translated other than from a technical point of view (identifying the locale from URL), so I will go ahead and disable the german translation for now.

**Comment by s-pace** [comment]
👋 @oliverguenther 

The issue here is [that the page](https://docs.openproject-edge.com/getting-started/sign-in-registration/#sign-in-and-registration) does not contain an element matching the `lvl2` selector.

d6b73dd will help remove these duplicated elements. Let us know if these changes suits you well.

**Comment by oliverguenther** [comment]
I see, heartful thanks again your quick assitance :bowing_man: . I hope we can be more self-sufficient in the next updates to this config.

**Pull request merged**
