### PR TITLE
Revert #3464.

### PR DESCRIPTION
**Pull request by mattstein**
Sorry for the noise—this was a bad idea and made things worse. 🤦‍♂️

### CODE REVIEW

**Comment by shortcuts** [comment]
Hi, 

Could you please give me a detailed example of what should be accomplished?

Thanks

**Comment by mattstein** [comment]
Hi @shortcuts, thanks for merging! I noted what I was attempting to solve in this issue:
https://github.com/pixelandtonic/vuepress-theme-craftdocs/issues/22

I’m not sure if it’s more an issue of UI or indexing, and reverting this change doesn’t solve it but gets us back to a preferable form of problem until I can spend more time on it.

**Comment by shortcuts** [comment]
Hi!

So, for now having `.sidebar-heading.open` as a `lvl1` selector could help but it will display something like `craft\commerce\elements`. 

Best solution would be to have a special selector around the last part (id, class, etc.)

**Comment by mattstein** [comment]
Thanks for the quick response, @shortcuts!

That `.theme-default-content .router-link-exact-active` selector worked perfectly as a `lvl1` selector in terms of what I intended to index—it’s the VuePress DocSearch UI that became uncomfortably cluttered and harder to read.

**Pull request merged**
