### PR TITLE
Update tiny.json

### PR DESCRIPTION
**Pull request by idooo**
# Pull request motivation(s)
Hi Algolia team! This PR is to update a few things for our DocSearch config. We've just added a new version of documentation and want to search it by a separate tag
Thank you for the awesome product!

### CODE REVIEW

**Comment by s-pace** [comment]
👋 @idooo 

It seems that your pages https://www.tiny.cloud/docs-4x/ are not available yet. Could you please ping me here once it is available?

Thanks

**Comment by idooo** [comment]
@s-pace thank you.. we made them available today

**Comment by s-pace** [comment]
👋 @idooo ,

We couldn't find any pages builded following this pattern `https://www.tiny.cloud/docs-4x/`, except [the first page](https://www.tiny.cloud/docs-4x/). Every nested links are redirecting to https://www.tiny.cloud/docs/

Could you add some meta tags within your page in order to better handle version? You can find some [help regarding how to do so here](https://community.algolia.com/docsearch/recommended-configuration.html#introduces-global-information-as-meta-tags).

Let us know

**Comment by idooo** [comment]
This should be fixed now. Sorry for the inconvenience =)

**Comment by s-pace** [comment]
@idooo changes are live :)

**Pull request merged**
