### PR TITLE
Update akeneo-help.json

### PR DESCRIPTION
**Pull request by momoss**
# Pull request motivation(s)

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### CODE REVIEW

**Comment by s-pace** [comment]
👋 @momoss 

`https://help.akeneo.com/index-pim.html` and `onboarder` pages are not available yet. 

When do you plan to release these pages?

**Comment by momoss** [comment]
@s-pace It's released 👌, thank's for your feedback

**Comment by s-pace** [comment]
`https://help.akeneo.com/index-pim.html` is not up yet but otherwise it works well

**Comment by bgouraud** [comment]
@s-pace Sorry! It is https://help.akeneo.com/pim-index.html and not index-pim.html.

**Comment by bgouraud** [comment]
Can you change from your side or you need an other PR?

**Comment by s-pace** [comment]
@bgouraud Sure. Done ⬆️ 

This page is not matching any selectors. It will not be retrievable.

**Comment by momoss** [comment]
hi @s-pace, the 3 "sub sites" don't have any selectors on index page, but use the same templating:
docSearch-content tag
- [onboarder docSearch-content](https://github.com/akeneo/onboarder-helpcenter/search?q=docSearch-content&unscoped_q=docSearch-content)
- [portal docSearch-content](https://github.com/akeneo/portal-helpcenter/search?q=docSearch-content&unscoped_q=docSearch-content)
- [pim docSearch-content](https://github.com/akeneo/pim-helpcenter/search?q=docSearch-content&unscoped_q=docSearch-content)
and same for docSearch-mainTitle.

We have the selectors on articles page like:
-  [onboarder](https://help.akeneo.com/onboarder/articles/update-products.html),
- [portal](https://help.akeneo.com/portal/articles/extension-access.html)
- [pim](https://help.akeneo.com/articles/what-is-a-channel.html)

The only difference is for the onboarder and portal we put an url pointing on a directory like "https://help.akeneo.com/onboarder/"  in the config file, while for the pim tag we put a complete url like "https://help.akeneo.com/index-pim.html"

Maybe we can add additional selectors on this page `https://help.akeneo.com/pim-index.html`to help the engine, or update the config on the pim tag part?

**Comment by s-pace** [comment]
@momoss 

Could it be possible to change the URL to have some consistency. Every `pim` pages should be available under `https://help.akeneo.com/pim/`* URLs.

Otherwise you can add a meta tag `solution` in your DOM. It should be builded this way:

```html
<meta name="docsearch:solution" content="pim|onboarder|portal">
```

Let me know which solution suits you best. I will help you to update your configuration accordingly.

**Comment by momoss** [comment]
@s-pace 
As some of our customers/users has saved links on our pim helpcenter pages, we can't move folders/urls to `https://help.akeneo.com/pim/`.
So, can you give me more information about the way we should put the meta tag 

`<meta name="docsearch:solution" content="pim|onboarder|portal">`

Thank's

**Comment by momoss** [comment]
hi @s-pace, did you see previous comment  ⬆️

**Comment by s-pace** [comment]
👋 @momoss 

Depending of the page's category, please add in your DOM a meta tag:
```
<meta name="docsearch:solution" content="pim|onboarder|portal">
```

Then we will [merge this PR](https://github.com/algolia/docsearch-configs/pull/632), run the crawl, deploy it and then you will be able to add the following code to your JS snippet:
```js
algoliaOptions: { 'facetFilters': ["solution:$SOLUTION"] },
```

`$SOLUTION` will be replaced by the `solution` you want to restrain the scope of the search on. It will be either `pim`, `onboarder` or `portal`
For example, if you want to only display `pim` results:
```js
 docsearch({
          apiKey: '383063c398d4eb9df08945560d3d26fc',
          indexName: 'akeneo-help',
          inputSelector: '#docSearch-input',
          debug: false, // Set debug to true if you want to inspect the dropdown
          algoliaOptions: {
            'facetFilters': ["solution:pim"]
          }
      });
```

Please ping me in the PR and we will deploy it as soon as possible.

**Comment by momoss** [comment]
hi @s-pace, it is deploy from our side 👌, so you can merge and deploy.

thank's in advance

**Comment by s-pace** [comment]
@momoss ✅

**Comment by momoss** [comment]
🎉 thank's a lot @s-pace it work perfectly 🎉

**Pull request merged**
