### PR TITLE
Remove library-filtering for helpOM

### PR DESCRIPTION
**Pull request by beutlich**
Give up on library-filtering for helpOM 😢

### CODE REVIEW

**Comment by s-pace** [comment]
What is the exact URL you want to target?

**Comment by beutlich** [comment]
https://doc.modelica.org/Modelica%203.2.3/Resources/helpOM/ contains the HTML files from five different libraries: Complex, Modelica, ModelicaServices, ModelicaReference and ObsoleteModelica3. Each HTML file starts with the name of the library, e.g., Modelica.html, Modelica.UsersGuide.html, Modelica.Utilities.Examples.html etc. all belong to library Modelica. I am struggling to figure out proper URL patterns if Modelica.html and ModelicaServices.html are located in the same directory, but should be matched by different regular URL expressions. The trouble is, that "ModelicaServices" starts also with "Modelica", such that "Modelica" already covers all matches of "ModelicaServices".

**Comment by s-pace** [comment]
Ok. So put the most specific `start_urls` first since we use the first item matching.

**Comment by beutlich** [comment]
That's what I already did. Also in sitemap.xml I sorted to have the more-specific files first.

**Comment by beutlich** [comment]
@s-pace Did you have a look at it meanwhile? Thanks.

**Comment by s-pace** [comment]
Yes. The tagging is working well. 
Example of a record extracted from these pages
image


Can you have another look please?

**Comment by s-pace** [comment]
Closing it since we need a follow up. Feel free to reopen if needed

**Comment by beutlich** [comment]
Sorry, I was afk for the bank holiday.

Please go to https://doc.modelica.org/index-new.html and type exit in teh search field:

grafik

The options are set:

```js
algoliaOptions: {
          hitsPerPage: 16,
          "facetFilters": ["version:3.2.3", "tool:OM", "library:ModelicaServices"] // Test only for https://github.com/algolia/docsearch-configs/pull/1948
        }
```

Why is https://doc.modelica.org/Modelica%203.2.3/Resources/helpOM/ModelicaServices.System.exit.html not found?

**Pull request closed without merging**
