### PR TITLE
update pkgdown config

### PR DESCRIPTION
**Pull request by jayhesselberth**
this PR updates the pkgdown config to keep up with changes in r-lib/pkgdown#639

### CODE REVIEW

**Comment by s-pace** [comment]
Let's have a look

**Comment by s-pace** [comment]
👋 @jayhesselberth  cc @hadley 

This configuration looks very custom. Would be better if you could make you content fit an easier configuration.

It is live, let me know if these changes suits you well.

What are the reason for changing `attributesToRetrieve`?

**Comment by jayhesselberth** [comment]
I need `url_without_anchor`, which is undefined unless I specify custom `attributesToRetrieve`.

**Comment by s-pace** [comment]
Make sense, please try to build your documentation in order to simplify the configuration. @jayhesselberth

**Pull request merged**
