### PR TITLE
fix config for dr-dk

### PR DESCRIPTION
**Pull request by krep-dr**
# Pull request motivation(s)
Fix config for scraper

### What is the current behaviour?
The start url is not correct

### CODE REVIEW

**Comment by shortcuts** [comment]
Hi there,

Is that a private URL?

It seems unreachable/doesn't redirect

**Comment by krep-dr** [comment]
yes, the site is behind an ip filter. But we have whitelisted the ip from here https://www.algolia.com/doc/tools/crawler/troubleshooting/faq/#what-ip-address-can-i-use-for-ip-whitelisting

**Comment by shortcuts** [comment]
@krep-dr Sorry but this is related to the Crawler (https://www.algolia.com/products/crawler/). With DocSearch, your website have to be completely accessible and free to use to meet our policy. https://docsearch.algolia.com/docs/who-can-apply#the-checklist

**Comment by krep-dr** [comment]
ah, sorry I missed that part

**Pull request closed without merging**
