### PR TITLE
Removing RightScale policies from the stop urls

### PR DESCRIPTION
**Pull request by bharatrightscale**
RightScale specific change to remove previously added check.

# Pull request motivation(s)

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### CODE REVIEW

**Comment by bharatrightscale** [comment]
Please don't merge till @crunis approves it.

**Comment by s-pace** [comment]
👋 @crunis , any news?

**Comment by bharatrightscale** [comment]
@s-pace please go ahead and merge. Thanks. 

On a separate note, are you guys working on making this better so we don't have to submit a PR to algolia? Maybe some kind of configuration that we control.

**Comment by s-pace** [comment]
@bharatrightscale 

Thank you. We are working on having it self serve but this is required if we want to provide you the best search experience.

 Currently deploying

**Comment by bharatrightscale** [comment]
Thanks. Do you know how long it takes for the change to take effect after the merge?

**Comment by s-pace** [comment]
Live

**Comment by bharatrightscale** [comment]
Perfect thanks.

**Comment by bharatrightscale** [comment]
@s-pace doesn't look like the search is working. Is this change merged and working?

**Comment by s-pace** [comment]
Are you sure? @bharatrightscale

**Comment by bharatrightscale** [comment]
Yes. You can search for anything "policies" or "policy" and nothing shows up from the pages under the directory /policies*

docs.rightscale.com

**Comment by s-pace** [comment]
Please sent us the link of the missing pages.

If they aren't crawled, it is because they aren't referenced from any crawled pages.

**Comment by bharatrightscale** [comment]
All pages under this path are not showing up. 

http://docs.rightscale.com/policies/

They did before we updated the config to stop crawling them.

**Comment by s-pace** [comment]
I can confirm you that they aren't referenced from another then.

**Pull request merged**
