### PR TITLE
Update pilosa

### PR DESCRIPTION
**Pull request by codysoyland**
# Pull request motivation(s)

Update pilosa config to include latest documentation version.

### What is the current behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

### CODE REVIEW

**Comment by s-pace** [comment]
👋 @codysoyland 

Looks like your `v0.10` version pages aren't available yet. Is it expected?

**Comment by codysoyland** [comment]
Hi @s-pace, thanks for responding so quickly. I did things a bit out of order, so the website was *just* updated.

Thanks!
Cody

**Comment by s-pace** [comment]
You are welcome,
Makes sense, just ping here when it is ready, I will update it accordingly (no rush, we will be noticed of the change of `nb_hits` otherwise)

**Comment by s-pace** [comment]
✅ 👍

**Pull request merged**
