### PR TITLE
Update princexml.json.

### PR DESCRIPTION
**Pull request by mikeday**
Updating princexml.json as to avoid duplicate results in search from old docs.

### CODE REVIEW

**Comment by shortcuts** [comment]
Hey, feel free to merge master and ping me when done

**Comment by mikeday** [comment]
I don't have write access, how is this achieved?

**Comment by shortcuts** [comment]
Hey, you need to fork the project and submit changes from your own repository in order to do so, see: https://docs.github.com/en/get-started/exploring-projects-on-github/finding-ways-to-contribute-to-open-source-on-github

**Comment by mikeday** [comment]
This pull request passes the checks and has no conflicts, can you merge it now?

**Pull request merged**
