### PR TITLE
Update konvajs.json

### PR DESCRIPTION
**Pull request by lavrton**
# Pull request motivation(s)

Add sitemap, change the main selector

### CODE REVIEW

**Comment by s-pace** [comment]
👋 @lavrton 

The issue you are struggling with doesn't come from the selectors. I will troubleshoot and will let you know what is exactly going on.

**Comment by s-pace** [comment]
👋 @lavrton, It looks like your /docs/ pages can't be properly parsed thank to [lxml api](https://lxml.de/3.1/index.html). It does only impact these pages. Do you have any clue that might explain it?

**Comment by lavrton** [comment]
That makes sense. Looks like HTML was no 100% valid. I fixed it I hope at next indexing it will work just fine.

**Comment by s-pace** [comment]
Ok thanks. Closing it in the meantime. Feel free to submit another PR

**Pull request closed without merging**
