### PR TITLE
Update symfony.json

### PR DESCRIPTION
**Pull request by javiereguiluz**
Hi,

This PR proposes some changes in the config search of symfony.com.

-----

**I have a question** about one change:

We have a book published into several languages with these URL patterns:

```
https://symfony.com/doc/current/the-fast-track/en/...
https://symfony.com/doc/current/the-fast-track/es/...
https://symfony.com/doc/current/the-fast-track/fr/...
https://symfony.com/doc/current/the-fast-track/de/...
[...]
```

We want to **exclude all books except the English one**. I propose the following config. Is it correct for our purpose?

```
{
  "start_urls": [
    {
      "url": "https://symfony.com/doc/.*/the-fast-track/(?P<language>.*?)/.*",
      "variables": {
        "language": ["en"]
      },
    }
  ],
  "stop_urls": [
    "https://symfony.com/doc/.*/the-fast-track/.*/.*"
  ],
}
```

Thanks for your time reviewing this!

### CODE REVIEW

**Comment by shortcuts** [comment]
> We have a book published into several languages with these URL patterns

Unless it's available on multiple versions, I think keeping the URL simple is best: see [this commit](https://github.com/algolia/docsearch-configs/pull/4647/commits/2396b1d19b0cc9c9e1c23319d72605682f5ce369#diff-7fa388b07175a3d280d0f72a8c59f4deb5ca80c60f16ca20bfea7ec730b16bbeR17)

> We want to exclude all books except the English one.

I've simplified the `stop_urls` and handled it with a negative regex, which should do the trick! see [this commit](https://github.com/algolia/docsearch-configs/pull/4647/commits/2396b1d19b0cc9c9e1c23319d72605682f5ce369#diff-7fa388b07175a3d280d0f72a8c59f4deb5ca80c60f16ca20bfea7ec730b16bbeR64-R66)

**Comment by javiereguiluz** [comment]
Fantastic! Clément, thanks so much for taking care of fixing and improving the proposed changes. This is now ready on our side. Thanks a lot!

**Comment by shortcuts** [comment]
Cool! A crawl is queued after the merge, note that symfony have a pretty big index so it might take a bit of time to complete :D

**Comment by shortcuts** [comment]
Feel free to ping me in a few hours if you want to know how far it is in the process, or if you have feedbacks on the final results :)

**Comment by javiereguiluz** [comment]
Thanks for providing this fantastic service for open source projects and thanks for your stellar support!

**Pull request merged**
